/**
 * Open-source licences, for the About screen.
 *
 * GENERATED FILE — do not edit by hand.
 * Regenerate with ./scripts/generate-licences.sh after changing dependencies.
 */

export type Licence = {
    name: string;
    version: string;
    licence: string;
};

export const LICENCES: readonly Licence[] = [
    {name: "@babel/code-frame", version: "7.29.7", licence: "MIT"},
    {name: "@babel/compat-data", version: "7.29.7", licence: "MIT"},
    {name: "@babel/core", version: "7.29.7", licence: "MIT"},
    {name: "@babel/generator", version: "7.29.8", licence: "MIT"},
    {name: "@babel/helper-annotate-as-pure", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helper-compilation-targets", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helper-create-class-features-plugin", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helper-create-regexp-features-plugin", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helper-define-polyfill-provider", version: "0.6.8", licence: "MIT"},
    {name: "@babel/helper-globals", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helper-member-expression-to-functions", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helper-module-imports", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helper-module-transforms", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helper-optimise-call-expression", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helper-plugin-utils", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helper-remap-async-to-generator", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helper-replace-supers", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helper-skip-transparent-expression-wrappers", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helper-string-parser", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helper-validator-identifier", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helper-validator-option", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helper-wrap-function", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helpers", version: "7.29.7", licence: "MIT"},
    {name: "@babel/parser", version: "7.29.8", licence: "MIT"},
    {name: "@babel/plugin-proposal-decorators", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-proposal-export-default-from", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-syntax-decorators", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-syntax-dynamic-import", version: "7.8.3", licence: "MIT"},
    {name: "@babel/plugin-syntax-export-default-from", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-syntax-flow", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-syntax-jsx", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-syntax-nullish-coalescing-operator", version: "7.8.3", licence: "MIT"},
    {name: "@babel/plugin-syntax-optional-chaining", version: "7.8.3", licence: "MIT"},
    {name: "@babel/plugin-syntax-typescript", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-arrow-functions", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-async-generator-functions", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-async-to-generator", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-block-scoping", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-class-properties", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-class-static-block", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-classes", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-destructuring", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-export-namespace-from", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-flow-strip-types", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-for-of", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-logical-assignment-operators", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-modules-commonjs", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-named-capturing-groups-regex", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-nullish-coalescing-operator", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-object-rest-spread", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-optional-catch-binding", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-optional-chaining", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-parameters", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-private-methods", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-private-property-in-object", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-react-display-name", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-react-jsx", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-react-jsx-development", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-react-pure-annotations", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-runtime", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-shorthand-properties", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-template-literals", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-typescript", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-unicode-regex", version: "7.29.7", licence: "MIT"},
    {name: "@babel/preset-typescript", version: "7.29.7", licence: "MIT"},
    {name: "@babel/runtime", version: "7.29.7", licence: "MIT"},
    {name: "@babel/template", version: "7.29.7", licence: "MIT"},
    {name: "@babel/traverse", version: "7.29.8", licence: "MIT"},
    {name: "@babel/types", version: "7.29.8", licence: "MIT"},
    {name: "@backpackapp-io/react-native-toast", version: "0.15.1", licence: "MIT"},
    {name: "@egjs/hammerjs", version: "2.0.17", licence: "MIT"},
    {name: "@expo-google-fonts/material-symbols", version: "0.4.44", licence: "MIT AND Apache-2.0"},
    {name: "@expo/cli", version: "not installed", licence: "unknown"},
    {name: "@expo/config", version: "57.0.9", licence: "MIT"},
    {name: "@expo/config-plugins", version: "57.0.9", licence: "MIT"},
    {name: "@expo/config-types", version: "57.0.2", licence: "MIT"},
    {name: "@expo/devtools", version: "57.0.1", licence: "MIT"},
    {name: "@expo/dom-webview", version: "57.0.1", licence: "MIT"},
    {name: "@expo/env", version: "2.4.2", licence: "MIT"},
    {name: "@expo/expo-modules-macros-plugin", version: "0.6.1", licence: "MIT"},
    {name: "@expo/fingerprint", version: "0.20.10", licence: "MIT"},
    {name: "@expo/image-utils", version: "0.11.5", licence: "MIT"},
    {name: "@expo/json-file", version: "11.0.1", licence: "MIT"},
    {name: "@expo/local-build-cache-provider", version: "57.0.7", licence: "MIT"},
    {name: "@expo/log-box", version: "57.0.3", licence: "MIT"},
    {name: "@expo/metro", version: "56.0.2", licence: "MIT"},
    {name: "@expo/metro-config", version: "57.0.10", licence: "MIT"},
    {name: "@expo/metro-runtime", version: "57.0.13", licence: "MIT"},
    {name: "@expo/plist", version: "0.8.1", licence: "MIT"},
    {name: "@expo/require-utils", version: "57.0.5", licence: "MIT"},
    {name: "@expo/schema-utils", version: "57.0.2", licence: "MIT"},
    {name: "@expo/sdk-runtime-versions", version: "1.0.0", licence: "MIT"},
    {name: "@expo/spawn-async", version: "1.8.0", licence: "MIT"},
    {name: "@expo/ui", version: "57.0.13", licence: "MIT"},
    {name: "@expo/vector-icons", version: "15.1.1", licence: "MIT"},
    {name: "@floating-ui/core", version: "1.8.0", licence: "MIT"},
    {name: "@floating-ui/react-dom", version: "not installed", licence: "unknown"},
    {name: "@floating-ui/react-native", version: "0.10.10", licence: "MIT"},
    {name: "@floating-ui/utils", version: "0.2.12", licence: "MIT"},
    {name: "@isaacs/ttlcache", version: "1.4.1", licence: "ISC"},
    {name: "@jest/schemas", version: "29.6.3", licence: "MIT"},
    {name: "@jest/types", version: "29.6.3", licence: "MIT"},
    {name: "@jridgewell/gen-mapping", version: "0.3.13", licence: "MIT"},
    {name: "@jridgewell/remapping", version: "2.3.5", licence: "MIT"},
    {name: "@jridgewell/resolve-uri", version: "3.1.2", licence: "MIT"},
    {name: "@jridgewell/source-map", version: "0.3.11", licence: "MIT"},
    {name: "@jridgewell/sourcemap-codec", version: "1.5.5", licence: "MIT"},
    {name: "@jridgewell/trace-mapping", version: "0.3.31", licence: "MIT"},
    {name: "@miblanchard/react-native-slider", version: "2.6.0", licence: "MIT"},
    {name: "@radix-ui/primitive", version: "1.1.7", licence: "MIT"},
    {name: "@radix-ui/react-collection", version: "1.1.15", licence: "MIT"},
    {name: "@radix-ui/react-compose-refs", version: "1.1.5", licence: "MIT"},
    {name: "@radix-ui/react-context", version: "1.2.2", licence: "MIT"},
    {name: "@radix-ui/react-dialog", version: "1.1.23", licence: "MIT"},
    {name: "@radix-ui/react-direction", version: "1.1.4", licence: "MIT"},
    {name: "@radix-ui/react-dismissable-layer", version: "1.1.19", licence: "MIT"},
    {name: "@radix-ui/react-focus-guards", version: "1.1.6", licence: "MIT"},
    {name: "@radix-ui/react-focus-scope", version: "1.1.16", licence: "MIT"},
    {name: "@radix-ui/react-id", version: "1.1.4", licence: "MIT"},
    {name: "@radix-ui/react-portal", version: "1.1.17", licence: "MIT"},
    {name: "@radix-ui/react-presence", version: "1.1.10", licence: "MIT"},
    {name: "@radix-ui/react-primitive", version: "2.1.10", licence: "MIT"},
    {name: "@radix-ui/react-roving-focus", version: "1.1.19", licence: "MIT"},
    {name: "@radix-ui/react-slot", version: "1.3.3", licence: "MIT"},
    {name: "@radix-ui/react-tabs", version: "1.1.21", licence: "MIT"},
    {name: "@radix-ui/react-use-callback-ref", version: "1.1.4", licence: "MIT"},
    {name: "@radix-ui/react-use-controllable-state", version: "1.2.6", licence: "MIT"},
    {name: "@radix-ui/react-use-effect-event", version: "0.0.5", licence: "MIT"},
    {name: "@radix-ui/react-use-is-hydrated", version: "0.1.3", licence: "MIT"},
    {name: "@radix-ui/react-use-layout-effect", version: "1.1.4", licence: "MIT"},
    {name: "@react-native-masked-view/masked-view", version: "0.3.2", licence: "MIT"},
    {name: "@react-native/assets-registry", version: "0.86.2", licence: "MIT"},
    {name: "@react-native/babel-plugin-codegen", version: "0.86.2", licence: "MIT"},
    {name: "@react-native/codegen", version: "0.86.2", licence: "MIT"},
    {name: "@react-native/community-cli-plugin", version: "0.86.2", licence: "MIT"},
    {name: "@react-native/debugger-frontend", version: "0.86.2", licence: "BSD-3-Clause"},
    {name: "@react-native/debugger-shell", version: "0.86.2", licence: "MIT"},
    {name: "@react-native/dev-middleware", version: "0.86.2", licence: "MIT"},
    {name: "@react-native/gradle-plugin", version: "0.86.2", licence: "MIT"},
    {name: "@react-native/js-polyfills", version: "0.86.2", licence: "MIT"},
    {name: "@react-native/normalize-color", version: "2.1.0", licence: "MIT"},
    {name: "@react-native/normalize-colors", version: "0.83.2", licence: "MIT"},
    {name: "@react-native/virtualized-lists", version: "0.86.2", licence: "MIT"},
    {name: "@sinclair/typebox", version: "0.27.12", licence: "MIT"},
    {name: "@tamagui/accordion", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/adapt", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/alert-dialog", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/animate", version: "2.7.7", licence: "MIT"},
    {name: "@tamagui/animate-presence", version: "2.7.7", licence: "MIT"},
    {name: "@tamagui/animation-helpers", version: "2.7.7", licence: "MIT"},
    {name: "@tamagui/animations-css", version: "2.7.7", licence: "MIT"},
    {name: "@tamagui/animations-motion", version: "2.7.7", licence: "MIT"},
    {name: "@tamagui/animations-react-native", version: "2.7.7", licence: "MIT"},
    {name: "@tamagui/animations-reanimated", version: "2.7.7", licence: "MIT"},
    {name: "@tamagui/avatar", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/button", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/card", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/checkbox", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/checkbox-headless", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/collapsible", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/collection", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/colors", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/compose-refs", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/config", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/config-default", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/constants", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/context-menu", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/core", version: "2.7.7", licence: "MIT"},
    {name: "@tamagui/create-context", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/create-menu", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/create-theme", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/cubic-bezier-animator", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/dialog", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/dismissable", version: "not installed", licence: "unknown"},
    {name: "@tamagui/element", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/elements", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/fake-react-native", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/floating", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/focus-guard", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/focus-scope", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/focusable", version: "2.7.7", licence: "MIT"},
    {name: "@tamagui/font-inter", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/font-silkscreen", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/font-size", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/form", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/get-button-sized", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/get-font-sized", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/get-token", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/group", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/helpers", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/helpers-tamagui", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/image", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/input", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/is-equal-shallow", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/label", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/linear-gradient", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/list-item", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/menu", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/native", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/normalize-css-color", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/polyfill-dev", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/popover", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/popper", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/portal", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/progress", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/radio-group", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/radio-headless", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/react-native-media-driver", version: "2.7.7", licence: "MIT"},
    {name: "@tamagui/react-native-use-pressable", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/remove-scroll", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/roving-focus", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/scroll-view", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/select", version: "not installed", licence: "unknown"},
    {name: "@tamagui/separator", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/shapes", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/sheet", version: "2.7.7", licence: "MIT"},
    {name: "@tamagui/shorthands", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/simple-hash", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/sizable-context", version: "2.7.7", licence: "MIT"},
    {name: "@tamagui/slider", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/spacer", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/spinner", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/stacks", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/start-transition", version: "2.7.7", licence: "MIT"},
    {name: "@tamagui/switch", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/switch-headless", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/tabs", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/text", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/theme", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/theme-builder", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/themes", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/timer", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/toast", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/toggle-group", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/tooltip", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/types", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/use-async", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/use-callback-ref", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/use-constant", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/use-controllable-state", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/use-debounce", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/use-did-finish-ssr", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/use-direction", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/use-element-layout", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/use-event", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/use-force-update", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/use-keyboard-visible", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/use-presence", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/use-previous", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/use-window-dimensions", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/visually-hidden", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/web", version: "2.7.7", licence: "MIT"},
    {name: "@tamagui/z-index-stack", version: "2.7.7", licence: "See package"},
    {name: "@types/hammerjs", version: "2.0.46", licence: "MIT"},
    {name: "@types/istanbul-lib-coverage", version: "2.0.6", licence: "MIT"},
    {name: "@types/istanbul-lib-report", version: "3.0.3", licence: "MIT"},
    {name: "@types/istanbul-reports", version: "3.0.4", licence: "MIT"},
    {name: "@types/node", version: "26.2.0", licence: "MIT"},
    {name: "@types/react", version: "19.2.18", licence: "MIT"},
    {name: "@types/react-test-renderer", version: "19.1.0", licence: "MIT"},
    {name: "@types/yargs", version: "17.0.35", licence: "MIT"},
    {name: "@types/yargs-parser", version: "21.0.3", licence: "MIT"},
    {name: "@ungap/structured-clone", version: "1.3.3", licence: "ISC"},
    {name: "@xmldom/xmldom", version: "0.8.14", licence: "MIT"},
    {name: "@yarnpkg/lockfile", version: "1.1.0", licence: "BSD-2-Clause"},
    {name: "abort-controller", version: "3.0.0", licence: "MIT"},
    {name: "accepts", version: "2.0.0", licence: "MIT"},
    {name: "acorn", version: "8.18.0", licence: "MIT"},
    {name: "agent-base", version: "6.0.2", licence: "MIT"},
    {name: "anser", version: "1.4.10", licence: "MIT"},
    {name: "ansi-regex", version: "5.0.1", licence: "MIT"},
    {name: "ansi-styles", version: "4.3.0", licence: "MIT"},
    {name: "arg", version: "5.0.2", licence: "MIT"},
    {name: "aria-hidden", version: "1.2.6", licence: "MIT"},
    {name: "asap", version: "2.0.6", licence: "MIT"},
    {name: "await-lock", version: "2.2.2", licence: "MIT"},
    {name: "babel-plugin-polyfill-corejs2", version: "0.4.17", licence: "MIT"},
    {name: "babel-plugin-polyfill-corejs3", version: "0.13.0", licence: "MIT"},
    {name: "babel-plugin-polyfill-regenerator", version: "0.6.8", licence: "MIT"},
    {name: "babel-plugin-react-compiler", version: "1.0.0", licence: "MIT"},
    {name: "babel-plugin-react-native-web", version: "0.21.2", licence: "MIT"},
    {name: "babel-plugin-syntax-hermes-parser", version: "0.36.1", licence: "MIT"},
    {name: "babel-plugin-transform-flow-enums", version: "0.0.2", licence: "MIT"},
    {name: "babel-preset-expo", version: "57.0.8", licence: "MIT"},
    {name: "balanced-match", version: "4.0.4", licence: "MIT"},
    {name: "base64-js", version: "1.5.1", licence: "MIT"},
    {name: "baseline-browser-mapping", version: "2.11.16", licence: "Apache-2.0"},
    {name: "big-integer", version: "1.6.52", licence: "Unlicense"},
    {name: "boolbase", version: "1.0.0", licence: "ISC"},
    {name: "bplist-creator", version: "0.1.0", licence: "MIT"},
    {name: "bplist-parser", version: "0.3.1", licence: "MIT"},
    {name: "brace-expansion", version: "5.0.9", licence: "MIT"},
    {name: "braces", version: "3.0.3", licence: "MIT"},
    {name: "browserslist", version: "4.28.8", licence: "MIT"},
    {name: "bser", version: "2.1.1", licence: "Apache-2.0"},
    {name: "buffer", version: "6.0.3", licence: "MIT"},
    {name: "buffer-from", version: "1.1.2", licence: "MIT"},
    {name: "call-bind", version: "1.0.9", licence: "MIT"},
    {name: "call-bind-apply-helpers", version: "1.0.2", licence: "MIT"},
    {name: "call-bound", version: "1.0.4", licence: "MIT"},
    {name: "camelcase", version: "5.3.1", licence: "MIT"},
    {name: "caniuse-lite", version: "1.0.30001809", licence: "CC-BY-4.0"},
    {name: "chalk", version: "4.1.2", licence: "MIT"},
    {name: "chrome-launcher", version: "0.15.2", licence: "Apache-2.0"},
    {name: "chromium-edge-launcher", version: "0.3.0", licence: "Apache-2.0"},
    {name: "ci-info", version: "3.9.0", licence: "MIT"},
    {name: "client-only", version: "0.0.1", licence: "MIT"},
    {name: "cliui", version: "8.0.1", licence: "ISC"},
    {name: "color", version: "4.2.3", licence: "MIT"},
    {name: "color-convert", version: "2.0.1", licence: "MIT"},
    {name: "color-name", version: "1.1.4", licence: "MIT"},
    {name: "color-string", version: "1.9.1", licence: "MIT"},
    {name: "color2k", version: "2.0.4", licence: "MIT"},
    {name: "commander", version: "7.2.0", licence: "MIT"},
    {name: "connect", version: "3.7.0", licence: "MIT"},
    {name: "content-type", version: "2.1.0", licence: "MIT"},
    {name: "convert-source-map", version: "2.0.0", licence: "MIT"},
    {name: "core-js-compat", version: "3.50.0", licence: "MIT"},
    {name: "cross-spawn", version: "7.0.6", licence: "MIT"},
    {name: "css-select", version: "5.2.2", licence: "BSD-2-Clause"},
    {name: "css-tree", version: "1.1.3", licence: "MIT"},
    {name: "css-what", version: "6.2.2", licence: "BSD-2-Clause"},
    {name: "csstype", version: "3.2.3", licence: "MIT"},
    {name: "debug", version: "4.4.3", licence: "MIT"},
    {name: "decode-uri-component", version: "0.2.2", licence: "MIT"},
    {name: "deepmerge", version: "4.3.1", licence: "MIT"},
    {name: "define-data-property", version: "1.1.4", licence: "MIT"},
    {name: "depd", version: "2.0.0", licence: "MIT"},
    {name: "destroy", version: "1.2.0", licence: "MIT"},
    {name: "detect-libc", version: "2.1.2", licence: "Apache-2.0"},
    {name: "detect-node-es", version: "1.1.0", licence: "MIT"},
    {name: "dom-serializer", version: "2.0.0", licence: "MIT"},
    {name: "domelementtype", version: "2.3.0", licence: "BSD-2-Clause"},
    {name: "domhandler", version: "5.0.3", licence: "BSD-2-Clause"},
    {name: "domutils", version: "3.2.2", licence: "BSD-2-Clause"},
    {name: "dunder-proto", version: "1.0.1", licence: "MIT"},
    {name: "ee-first", version: "1.1.1", licence: "MIT"},
    {name: "electron-to-chromium", version: "1.5.412", licence: "ISC"},
    {name: "emoji-regex", version: "8.0.0", licence: "MIT"},
    {name: "encodeurl", version: "1.0.2", licence: "MIT"},
    {name: "entities", version: "6.0.1", licence: "BSD-2-Clause"},
    {name: "error-stack-parser", version: "2.1.4", licence: "MIT"},
    {name: "es-define-property", version: "1.0.1", licence: "MIT"},
    {name: "es-errors", version: "1.3.0", licence: "MIT"},
    {name: "es-object-atoms", version: "1.1.2", licence: "MIT"},
    {name: "escalade", version: "3.2.0", licence: "MIT"},
    {name: "escape-html", version: "1.0.3", licence: "MIT"},
    {name: "escape-string-regexp", version: "4.0.0", licence: "MIT"},
    {name: "etag", version: "1.8.1", licence: "MIT"},
    {name: "event-target-shim", version: "5.0.1", licence: "MIT"},
    {name: "expo", version: "57.0.16", licence: "MIT"},
    {name: "expo-asset", version: "57.0.14", licence: "MIT"},
    {name: "expo-build-properties", version: "57.0.14", licence: "MIT"},
    {name: "expo-clipboard", version: "57.0.1", licence: "MIT"},
    {name: "expo-constants", version: "57.0.14", licence: "MIT"},
    {name: "expo-dev-client", version: "57.0.15", licence: "MIT"},
    {name: "expo-dev-launcher", version: "57.0.15", licence: "MIT"},
    {name: "expo-dev-menu", version: "57.0.15", licence: "MIT"},
    {name: "expo-dev-menu-interface", version: "57.0.0", licence: "MIT"},
    {name: "expo-file-system", version: "57.0.5", licence: "MIT"},
    {name: "expo-font", version: "57.0.1", licence: "MIT"},
    {name: "expo-glass-effect", version: "57.0.1", licence: "MIT"},
    {name: "expo-json-utils", version: "57.0.1", licence: "MIT"},
    {name: "expo-keep-awake", version: "57.0.1", licence: "MIT"},
    {name: "expo-linking", version: "57.0.7", licence: "MIT"},
    {name: "expo-manifests", version: "57.0.1", licence: "MIT"},
    {name: "expo-modules-autolinking", version: "57.0.11", licence: "MIT"},
    {name: "expo-modules-core", version: "57.0.13", licence: "MIT"},
    {name: "expo-modules-jsi", version: "57.0.5", licence: "MIT"},
    {name: "expo-router", version: "57.0.16", licence: "MIT"},
    {name: "expo-server", version: "57.0.3", licence: "MIT"},
    {name: "expo-share-intent", version: "8.0.1", licence: "MIT"},
    {name: "expo-splash-screen", version: "57.0.8", licence: "MIT"},
    {name: "expo-sqlite", version: "57.0.1", licence: "MIT"},
    {name: "expo-status-bar", version: "57.0.1", licence: "MIT"},
    {name: "expo-symbols", version: "57.0.2", licence: "MIT"},
    {name: "expo-system-ui", version: "57.0.2", licence: "MIT"},
    {name: "expo-updates-interface", version: "57.0.1", licence: "MIT"},
    {name: "exponential-backoff", version: "3.1.3", licence: "Apache-2.0"},
    {name: "fast-deep-equal", version: "3.1.3", licence: "MIT"},
    {name: "fb-dotslash", version: "0.5.8", licence: "(MIT OR Apache-2.0)"},
    {name: "fb-watchman", version: "2.0.2", licence: "Apache-2.0"},
    {name: "fdir", version: "6.5.0", licence: "MIT"},
    {name: "fill-range", version: "7.1.1", licence: "MIT"},
    {name: "filter-obj", version: "1.1.0", licence: "MIT"},
    {name: "finalhandler", version: "1.1.2", licence: "MIT"},
    {name: "find-yarn-workspace-root", version: "2.0.0", licence: "Apache-2.0"},
    {name: "flow-enums-runtime", version: "0.0.6", licence: "MIT"},
    {name: "fontfaceobserver", version: "2.3.0", licence: "BSD-2-Clause"},
    {name: "fresh", version: "0.5.2", licence: "MIT"},
    {name: "fs-extra", version: "10.1.0", licence: "MIT"},
    {name: "function-bind", version: "1.1.2", licence: "MIT"},
    {name: "gensync", version: "1.0.0-beta.2", licence: "MIT"},
    {name: "get-caller-file", version: "2.0.5", licence: "ISC"},
    {name: "get-intrinsic", version: "1.3.0", licence: "MIT"},
    {name: "get-nonce", version: "1.0.1", licence: "MIT"},
    {name: "get-proto", version: "1.0.1", licence: "MIT"},
    {name: "getenv", version: "2.0.0", licence: "MIT"},
    {name: "glob", version: "13.0.6", licence: "BlueOak-1.0.0"},
    {name: "gopd", version: "1.2.0", licence: "MIT"},
    {name: "graceful-fs", version: "4.2.11", licence: "ISC"},
    {name: "has-flag", version: "4.0.0", licence: "MIT"},
    {name: "has-property-descriptors", version: "1.0.2", licence: "MIT"},
    {name: "has-symbols", version: "1.1.0", licence: "MIT"},
    {name: "hasown", version: "2.0.4", licence: "MIT"},
    {name: "hermes-compiler", version: "250829098.0.16", licence: "MIT"},
    {name: "hermes-estree", version: "0.36.1", licence: "MIT"},
    {name: "hermes-parser", version: "0.36.1", licence: "MIT"},
    {name: "hoist-non-react-statics", version: "3.3.2", licence: "BSD-3-Clause"},
    {name: "http-errors", version: "2.0.1", licence: "MIT"},
    {name: "https-proxy-agent", version: "5.0.1", licence: "MIT"},
    {name: "ieee754", version: "1.2.1", licence: "BSD-3-Clause"},
    {name: "ignore", version: "5.3.2", licence: "MIT"},
    {name: "inherits", version: "2.0.4", licence: "ISC"},
    {name: "invariant", version: "2.2.4", licence: "MIT"},
    {name: "is-arrayish", version: "0.2.1", licence: "MIT"},
    {name: "is-core-module", version: "2.16.2", licence: "MIT"},
    {name: "is-docker", version: "2.2.1", licence: "MIT"},
    {name: "is-fullwidth-code-point", version: "3.0.0", licence: "MIT"},
    {name: "is-number", version: "7.0.0", licence: "MIT"},
    {name: "is-wsl", version: "2.2.0", licence: "MIT"},
    {name: "isarray", version: "2.0.5", licence: "MIT"},
    {name: "isexe", version: "2.0.0", licence: "ISC"},
    {name: "jest-get-type", version: "29.6.3", licence: "MIT"},
    {name: "jest-util", version: "29.7.0", licence: "MIT"},
    {name: "jest-validate", version: "29.7.0", licence: "MIT"},
    {name: "jest-worker", version: "29.7.0", licence: "MIT"},
    {name: "jimp-compact", version: "0.16.1", licence: "MIT"},
    {name: "js-tokens", version: "4.0.0", licence: "MIT"},
    {name: "jsc-safe-url", version: "0.2.4", licence: "0BSD"},
    {name: "jsesc", version: "3.1.0", licence: "MIT"},
    {name: "json-stable-stringify", version: "1.3.0", licence: "MIT"},
    {name: "json5", version: "2.2.3", licence: "MIT"},
    {name: "jsonfile", version: "6.2.1", licence: "MIT"},
    {name: "jsonify", version: "0.0.1", licence: "Public Domain"},
    {name: "klaw-sync", version: "6.0.0", licence: "MIT"},
    {name: "leven", version: "3.1.0", licence: "MIT"},
    {name: "lighthouse-logger", version: "1.4.2", licence: "Apache-2.0"},
    {name: "lightningcss", version: "1.33.0", licence: "MPL-2.0"},
    {name: "lodash.debounce", version: "4.0.8", licence: "MIT"},
    {name: "lodash.throttle", version: "4.1.1", licence: "MIT"},
    {name: "loose-envify", version: "1.4.0", licence: "MIT"},
    {name: "lru-cache", version: "5.1.1", licence: "ISC"},
    {name: "makeerror", version: "1.0.12", licence: "BSD-3-Clause"},
    {name: "marky", version: "1.3.0", licence: "Apache-2.0"},
    {name: "math-intrinsics", version: "1.1.0", licence: "MIT"},
    {name: "mdn-data", version: "2.0.14", licence: "CC0-1.0"},
    {name: "memoize-one", version: "5.2.1", licence: "MIT"},
    {name: "merge-stream", version: "2.0.0", licence: "MIT"},
    {name: "metro", version: "0.84.5", licence: "MIT"},
    {name: "metro-babel-transformer", version: "0.84.5", licence: "MIT"},
    {name: "metro-cache", version: "0.84.5", licence: "MIT"},
    {name: "metro-cache-key", version: "0.84.5", licence: "MIT"},
    {name: "metro-config", version: "0.84.5", licence: "MIT"},
    {name: "metro-core", version: "0.84.5", licence: "MIT"},
    {name: "metro-file-map", version: "0.84.5", licence: "MIT"},
    {name: "metro-minify-terser", version: "0.84.5", licence: "MIT"},
    {name: "metro-resolver", version: "0.84.5", licence: "MIT"},
    {name: "metro-runtime", version: "0.84.5", licence: "MIT"},
    {name: "metro-source-map", version: "0.84.5", licence: "MIT"},
    {name: "metro-symbolicate", version: "0.84.5", licence: "MIT"},
    {name: "metro-transform-plugins", version: "0.84.5", licence: "MIT"},
    {name: "metro-transform-worker", version: "0.84.5", licence: "MIT"},
    {name: "micromatch", version: "4.0.8", licence: "MIT"},
    {name: "mime", version: "1.6.0", licence: "MIT"},
    {name: "mime-db", version: "1.52.0", licence: "MIT"},
    {name: "mime-types", version: "2.1.35", licence: "MIT"},
    {name: "minimatch", version: "10.2.6", licence: "BlueOak-1.0.0"},
    {name: "minimist", version: "1.2.8", licence: "MIT"},
    {name: "minipass", version: "7.1.3", licence: "BlueOak-1.0.0"},
    {name: "mkdirp", version: "1.0.4", licence: "MIT"},
    {name: "motion", version: "not installed", licence: "unknown"},
    {name: "ms", version: "2.1.3", licence: "MIT"},
    {name: "nanoid", version: "3.3.18", licence: "MIT"},
    {name: "negotiator", version: "1.1.0", licence: "MIT"},
    {name: "node-int64", version: "0.4.0", licence: "MIT"},
    {name: "node-releases", version: "2.0.53", licence: "MIT"},
    {name: "nth-check", version: "2.1.1", licence: "BSD-2-Clause"},
    {name: "nullthrows", version: "1.1.1", licence: "MIT"},
    {name: "ob1", version: "0.84.5", licence: "MIT"},
    {name: "object-keys", version: "1.1.1", licence: "MIT"},
    {name: "on-finished", version: "2.3.0", licence: "MIT"},
    {name: "open", version: "7.4.2", licence: "MIT"},
    {name: "parse-png", version: "2.1.0", licence: "MIT"},
    {name: "parseurl", version: "1.3.3", licence: "MIT"},
    {name: "patch-package", version: "8.0.1", licence: "MIT"},
    {name: "path-key", version: "3.1.1", licence: "MIT"},
    {name: "path-parse", version: "1.0.7", licence: "MIT"},
    {name: "path-scurry", version: "2.0.2", licence: "BlueOak-1.0.0"},
    {name: "picocolors", version: "1.1.1", licence: "ISC"},
    {name: "picomatch", version: "4.0.5", licence: "MIT"},
    {name: "plist", version: "3.1.1", licence: "MIT"},
    {name: "pngjs", version: "3.4.0", licence: "MIT"},
    {name: "postcss", version: "8.5.26", licence: "MIT"},
    {name: "pretty-format", version: "29.7.0", licence: "MIT"},
    {name: "promise", version: "8.3.0", licence: "MIT"},
    {name: "query-string", version: "7.1.3", licence: "MIT"},
    {name: "range-parser", version: "1.2.1", licence: "MIT"},
    {name: "react", version: "19.2.3", licence: "MIT"},
    {name: "react-devtools-core", version: "6.1.5", licence: "MIT"},
    {name: "react-dom", version: "19.2.3", licence: "MIT"},
    {name: "react-fast-compare", version: "3.2.2", licence: "MIT"},
    {name: "react-freeze", version: "1.0.4", licence: "MIT"},
    {name: "react-is", version: "19.2.8", licence: "MIT"},
    {name: "react-native", version: "0.86.2", licence: "MIT"},
    {name: "react-native-drawer-layout", version: "4.2.10", licence: "MIT"},
    {name: "react-native-gesture-handler", version: "2.32.0", licence: "MIT"},
    {name: "react-native-is-edge-to-edge", version: "1.3.1", licence: "MIT"},
    {name: "react-native-nfc-manager", version: "3.17.2", licence: "MIT"},
    {name: "react-native-reanimated", version: "4.5.1", licence: "MIT"},
    {name: "react-native-safe-area-context", version: "5.7.0", licence: "MIT"},
    {name: "react-native-screens", version: "4.26.2", licence: "MIT"},
    {name: "react-native-svg", version: "15.15.4", licence: "MIT"},
    {name: "react-native-teleport", version: "1.1.13", licence: "MIT"},
    {name: "react-native-uuid", version: "2.0.4", licence: "MIT"},
    {name: "react-native-worklets", version: "0.10.1", licence: "MIT"},
    {name: "react-refresh", version: "0.14.2", licence: "MIT"},
    {name: "react-remove-scroll", version: "2.7.2", licence: "MIT"},
    {name: "react-remove-scroll-bar", version: "2.3.8", licence: "MIT"},
    {name: "react-style-singleton", version: "2.2.3", licence: "MIT"},
    {name: "regenerate", version: "1.4.2", licence: "MIT"},
    {name: "regenerate-unicode-properties", version: "10.2.2", licence: "MIT"},
    {name: "regenerator-runtime", version: "0.13.11", licence: "MIT"},
    {name: "regexpu-core", version: "6.4.0", licence: "MIT"},
    {name: "regjsgen", version: "0.8.0", licence: "MIT"},
    {name: "regjsparser", version: "0.13.2", licence: "BSD-2-Clause"},
    {name: "require-directory", version: "2.1.1", licence: "MIT"},
    {name: "resolve", version: "1.22.12", licence: "MIT"},
    {name: "resolve-from", version: "5.0.0", licence: "MIT"},
    {name: "resolve-workspace-root", version: "2.0.1", licence: "MIT"},
    {name: "sax", version: "1.6.1", licence: "BlueOak-1.0.0"},
    {name: "scheduler", version: "0.27.0", licence: "MIT"},
    {name: "semver", version: "6.3.1", licence: "ISC"},
    {name: "send", version: "0.19.2", licence: "MIT"},
    {name: "serialize-error", version: "2.1.0", licence: "MIT"},
    {name: "serve-static", version: "1.16.3", licence: "MIT"},
    {name: "server-only", version: "0.0.1", licence: "MIT"},
    {name: "set-function-length", version: "1.2.2", licence: "MIT"},
    {name: "setprototypeof", version: "1.2.0", licence: "ISC"},
    {name: "sf-symbols-typescript", version: "2.2.0", licence: "MIT"},
    {name: "shallowequal", version: "1.1.0", licence: "MIT"},
    {name: "shebang-command", version: "2.0.0", licence: "MIT"},
    {name: "shebang-regex", version: "3.0.0", licence: "MIT"},
    {name: "shell-quote", version: "1.10.0", licence: "MIT"},
    {name: "simple-plist", version: "1.3.1", licence: "MIT"},
    {name: "simple-swizzle", version: "0.2.4", licence: "MIT"},
    {name: "slash", version: "3.0.0", licence: "MIT"},
    {name: "slugify", version: "1.6.9", licence: "MIT"},
    {name: "source-map", version: "0.6.1", licence: "BSD-3-Clause"},
    {name: "source-map-js", version: "1.2.1", licence: "BSD-3-Clause"},
    {name: "source-map-support", version: "0.5.13", licence: "MIT"},
    {name: "split-on-first", version: "1.1.0", licence: "MIT"},
    {name: "stackframe", version: "1.3.4", licence: "MIT"},
    {name: "stacktrace-parser", version: "0.1.11", licence: "MIT"},
    {name: "standard-navigation", version: "0.0.5", licence: "MIT"},
    {name: "statuses", version: "1.5.0", licence: "MIT"},
    {name: "stream-buffers", version: "2.2.0", licence: "Unlicense"},
    {name: "strict-uri-encode", version: "2.0.0", licence: "MIT"},
    {name: "string-width", version: "4.2.3", licence: "MIT"},
    {name: "strip-ansi", version: "6.0.1", licence: "MIT"},
    {name: "supports-color", version: "7.2.0", licence: "MIT"},
    {name: "supports-preserve-symlinks-flag", version: "1.0.0", licence: "MIT"},
    {name: "tamagui", version: "2.7.7", licence: "See package"},
    {name: "terser", version: "5.50.0", licence: "BSD-2-Clause"},
    {name: "throat", version: "5.0.0", licence: "MIT"},
    {name: "tinyglobby", version: "0.2.17", licence: "MIT"},
    {name: "tmp", version: "0.2.7", licence: "MIT"},
    {name: "tmpl", version: "1.0.5", licence: "BSD-3-Clause"},
    {name: "to-regex-range", version: "5.0.1", licence: "MIT"},
    {name: "toidentifier", version: "1.0.1", licence: "MIT"},
    {name: "tslib", version: "2.8.1", licence: "0BSD"},
    {name: "type-fest", version: "0.21.3", licence: "(MIT OR CC0-1.0)"},
    {name: "undici-types", version: "8.3.0", licence: "MIT"},
    {name: "unicode-canonical-property-names-ecmascript", version: "2.0.1", licence: "MIT"},
    {name: "unicode-match-property-ecmascript", version: "2.0.0", licence: "MIT"},
    {name: "unicode-match-property-value-ecmascript", version: "2.2.1", licence: "MIT"},
    {name: "unicode-property-aliases-ecmascript", version: "2.2.0", licence: "MIT"},
    {name: "universalify", version: "2.0.1", licence: "MIT"},
    {name: "unpipe", version: "1.0.0", licence: "MIT"},
    {name: "update-browserslist-db", version: "1.3.1", licence: "MIT"},
    {name: "use-callback-ref", version: "1.3.3", licence: "MIT"},
    {name: "use-latest-callback", version: "0.2.6", licence: "MIT"},
    {name: "use-sidecar", version: "1.1.3", licence: "MIT"},
    {name: "utils-merge", version: "1.0.1", licence: "MIT"},
    {name: "uuid", version: "7.0.3", licence: "MIT"},
    {name: "vaul", version: "1.1.2", licence: "MIT"},
    {name: "vlq", version: "1.0.1", licence: "MIT"},
    {name: "walker", version: "1.0.8", licence: "Apache-2.0"},
    {name: "warn-once", version: "0.1.1", licence: "MIT"},
    {name: "whatwg-fetch", version: "3.6.20", licence: "MIT"},
    {name: "whatwg-url-minimum", version: "0.1.2", licence: "MIT"},
    {name: "which", version: "2.0.2", licence: "ISC"},
    {name: "wrap-ansi", version: "7.0.0", licence: "MIT"},
    {name: "ws", version: "8.21.3", licence: "MIT"},
    {name: "xcode", version: "3.0.1", licence: "Apache-2.0"},
    {name: "xml2js", version: "0.6.0", licence: "MIT"},
    {name: "xmlbuilder", version: "15.1.1", licence: "MIT"},
    {name: "y18n", version: "5.0.8", licence: "ISC"},
    {name: "yallist", version: "3.1.1", licence: "ISC"},
    {name: "yaml", version: "2.9.0", licence: "ISC"},
    {name: "yargs", version: "17.7.3", licence: "MIT"},
    {name: "yargs-parser", version: "21.1.1", licence: "ISC"},
];
