/**
 * Open-source licences, for the About screen.
 *
 * GENERATED FILE — do not edit by hand.
 * Regenerate with `npm run generate-licences` after changing dependencies.
 */

export type Licence = {
    name: string;
    version: string;
    licence: string;
    /** The notice MIT and BSD both require reproducing, when one was found. */
    copyright?: string;
};

export const LICENCES: readonly Licence[] = [
    {name: "@babel/code-frame", version: "7.29.7", licence: "MIT"},
    {name: "@babel/compat-data", version: "7.29.7", licence: "MIT"},
    {name: "@babel/core", version: "7.29.7", licence: "MIT"},
    {name: "@babel/generator", version: "7.29.8", licence: "MIT"},
    {name: "@babel/helper-annotate-as-pure", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helper-compilation-targets", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helper-create-class-features-plugin", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helper-create-regexp-features-plugin", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helper-define-polyfill-provider", version: "0.6.8", licence: "MIT"},
    {name: "@babel/helper-globals", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helper-member-expression-to-functions", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helper-module-imports", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helper-module-transforms", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helper-optimise-call-expression", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helper-plugin-utils", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helper-remap-async-to-generator", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helper-replace-supers", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helper-skip-transparent-expression-wrappers", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helper-string-parser", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helper-validator-identifier", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helper-validator-option", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helper-wrap-function", version: "7.29.7", licence: "MIT"},
    {name: "@babel/helpers", version: "7.29.7", licence: "MIT"},
    {name: "@babel/parser", version: "7.29.8", licence: "MIT", copyright: "Copyright (C) 2012-2014 by various contributors (see AUTHORS)"},
    {name: "@babel/plugin-proposal-decorators", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-proposal-export-default-from", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-syntax-async-generators", version: "7.8.4", licence: "MIT"},
    {name: "@babel/plugin-syntax-bigint", version: "7.8.3", licence: "MIT"},
    {name: "@babel/plugin-syntax-class-properties", version: "7.12.13", licence: "MIT"},
    {name: "@babel/plugin-syntax-class-static-block", version: "7.14.5", licence: "MIT"},
    {name: "@babel/plugin-syntax-decorators", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-syntax-dynamic-import", version: "7.8.3", licence: "MIT"},
    {name: "@babel/plugin-syntax-export-default-from", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-syntax-flow", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-syntax-import-attributes", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-syntax-import-meta", version: "7.10.4", licence: "MIT"},
    {name: "@babel/plugin-syntax-json-strings", version: "7.8.3", licence: "MIT"},
    {name: "@babel/plugin-syntax-jsx", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-syntax-logical-assignment-operators", version: "7.10.4", licence: "MIT"},
    {name: "@babel/plugin-syntax-nullish-coalescing-operator", version: "7.8.3", licence: "MIT"},
    {name: "@babel/plugin-syntax-numeric-separator", version: "7.10.4", licence: "MIT"},
    {name: "@babel/plugin-syntax-object-rest-spread", version: "7.8.3", licence: "MIT"},
    {name: "@babel/plugin-syntax-optional-catch-binding", version: "7.8.3", licence: "MIT"},
    {name: "@babel/plugin-syntax-optional-chaining", version: "7.8.3", licence: "MIT"},
    {name: "@babel/plugin-syntax-private-property-in-object", version: "7.14.5", licence: "MIT"},
    {name: "@babel/plugin-syntax-top-level-await", version: "7.14.5", licence: "MIT"},
    {name: "@babel/plugin-syntax-typescript", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-arrow-functions", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-async-generator-functions", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-async-to-generator", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-block-scoping", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-class-properties", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-class-static-block", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-classes", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-destructuring", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-export-namespace-from", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-flow-strip-types", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-for-of", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-logical-assignment-operators", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-modules-commonjs", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-named-capturing-groups-regex", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-nullish-coalescing-operator", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-object-rest-spread", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-optional-catch-binding", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-optional-chaining", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-parameters", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-private-methods", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-private-property-in-object", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-react-display-name", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-react-jsx", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-react-jsx-development", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-react-jsx-self", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-react-jsx-source", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-react-pure-annotations", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-regenerator", version: "7.29.8", licence: "MIT"},
    {name: "@babel/plugin-transform-runtime", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-shorthand-properties", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-template-literals", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-typescript", version: "7.29.7", licence: "MIT"},
    {name: "@babel/plugin-transform-unicode-regex", version: "7.29.7", licence: "MIT"},
    {name: "@babel/preset-typescript", version: "7.29.7", licence: "MIT"},
    {name: "@babel/runtime", version: "7.29.7", licence: "MIT"},
    {name: "@babel/template", version: "7.29.7", licence: "MIT"},
    {name: "@babel/traverse", version: "7.29.8", licence: "MIT"},
    {name: "@babel/types", version: "7.29.8", licence: "MIT"},
    {name: "@backpackapp-io/react-native-toast", version: "0.13.0, 0.15.1", licence: "MIT", copyright: "Copyright (c) 2022 Nick DeBaise"},
    {name: "@bcoe/v8-coverage", version: "0.2.3", licence: "MIT", copyright: "Copyright \u00a9 2015-2017 Charles Samborski"},
    {name: "@egjs/hammerjs", version: "2.0.17", licence: "MIT", copyright: "Copyright (C) 2011-2017 by Jorik Tangelder (Eight Media)"},
    {name: "@expo-google-fonts/material-symbols", version: "0.4.44", licence: "MIT AND Apache-2.0", copyright: "Copyright (c) 2020 Expo"},
    {name: "@expo/cli", version: "57.0.18", licence: "MIT"},
    {name: "@expo/code-signing-certificates", version: "0.0.6", licence: "MIT"},
    {name: "@expo/config", version: "57.0.9", licence: "MIT"},
    {name: "@expo/config-plugins", version: "57.0.9", licence: "MIT"},
    {name: "@expo/config-types", version: "57.0.2", licence: "MIT"},
    {name: "@expo/devcert", version: "1.2.1", licence: "MIT"},
    {name: "@expo/devtools", version: "57.0.1", licence: "MIT"},
    {name: "@expo/dom-webview", version: "57.0.1", licence: "MIT"},
    {name: "@expo/env", version: "2.4.2", licence: "MIT"},
    {name: "@expo/expo-modules-macros-plugin", version: "0.6.1", licence: "MIT"},
    {name: "@expo/fingerprint", version: "0.20.10", licence: "MIT"},
    {name: "@expo/image-utils", version: "0.11.5", licence: "MIT"},
    {name: "@expo/inline-modules", version: "0.1.6", licence: "MIT"},
    {name: "@expo/json-file", version: "11.0.1", licence: "MIT"},
    {name: "@expo/local-build-cache-provider", version: "57.0.7", licence: "MIT"},
    {name: "@expo/log-box", version: "57.0.3", licence: "MIT"},
    {name: "@expo/metro", version: "56.0.2", licence: "MIT"},
    {name: "@expo/metro-config", version: "57.0.10", licence: "MIT"},
    {name: "@expo/metro-file-map", version: "57.0.2", licence: "MIT"},
    {name: "@expo/metro-runtime", version: "57.0.13", licence: "MIT"},
    {name: "@expo/osascript", version: "2.7.1", licence: "MIT"},
    {name: "@expo/package-manager", version: "1.13.1", licence: "MIT"},
    {name: "@expo/plist", version: "0.8.1", licence: "MIT"},
    {name: "@expo/prebuild-config", version: "57.0.14", licence: "MIT"},
    {name: "@expo/require-utils", version: "57.0.5", licence: "MIT"},
    {name: "@expo/router-server", version: "57.0.7", licence: "MIT"},
    {name: "@expo/schema-utils", version: "57.0.2", licence: "MIT"},
    {name: "@expo/sdk-runtime-versions", version: "1.0.0", licence: "MIT"},
    {name: "@expo/spawn-async", version: "1.8.0", licence: "MIT", copyright: "Copyright (c) 2015 650 Industries"},
    {name: "@expo/sudo-prompt", version: "9.3.2", licence: "MIT", copyright: "Copyright (c) 2015 Joran Dirk Greef"},
    {name: "@expo/ui", version: "57.0.13", licence: "MIT"},
    {name: "@expo/vector-icons", version: "15.1.1", licence: "MIT", copyright: "Copyright (c) 2015 Joel Arvidsson"},
    {name: "@expo/ws-tunnel", version: "2.0.0", licence: "MIT"},
    {name: "@expo/xcpretty", version: "4.4.4", licence: "BSD-3-Clause"},
    {name: "@floating-ui/core", version: "1.8.0", licence: "MIT"},
    {name: "@floating-ui/dom", version: "1.8.0", licence: "MIT"},
    {name: "@floating-ui/react-dom", version: "2.1.9", licence: "MIT"},
    {name: "@floating-ui/react-native", version: "0.10.10", licence: "MIT"},
    {name: "@floating-ui/utils", version: "0.2.12", licence: "MIT"},
    {name: "@isaacs/ttlcache", version: "1.4.1", licence: "ISC", copyright: "Copyright (c) 2022-2023 - Isaac Z. Schlueter and Contributors"},
    {name: "@istanbuljs/load-nyc-config", version: "1.1.0", licence: "ISC", copyright: "Copyright (c) 2019, Contributors"},
    {name: "@istanbuljs/schema", version: "0.1.6", licence: "MIT", copyright: "Copyright (c) 2019 CFWare, LLC"},
    {name: "@jest/console", version: "29.7.0", licence: "MIT"},
    {name: "@jest/core", version: "29.7.0", licence: "MIT"},
    {name: "@jest/create-cache-key-function", version: "29.7.0", licence: "MIT"},
    {name: "@jest/diff-sequences", version: "30.4.0", licence: "MIT"},
    {name: "@jest/environment", version: "29.7.0", licence: "MIT"},
    {name: "@jest/expect", version: "29.7.0", licence: "MIT"},
    {name: "@jest/expect-utils", version: "29.7.0", licence: "MIT"},
    {name: "@jest/fake-timers", version: "29.7.0", licence: "MIT"},
    {name: "@jest/get-type", version: "30.1.0", licence: "MIT"},
    {name: "@jest/globals", version: "29.7.0", licence: "MIT"},
    {name: "@jest/reporters", version: "29.7.0", licence: "MIT"},
    {name: "@jest/schemas", version: "29.6.3, 30.4.1", licence: "MIT"},
    {name: "@jest/source-map", version: "29.6.3", licence: "MIT"},
    {name: "@jest/test-result", version: "29.7.0", licence: "MIT"},
    {name: "@jest/test-sequencer", version: "29.7.0", licence: "MIT"},
    {name: "@jest/transform", version: "29.7.0", licence: "MIT"},
    {name: "@jest/types", version: "29.6.3", licence: "MIT"},
    {name: "@jridgewell/gen-mapping", version: "0.3.13", licence: "MIT", copyright: "Copyright 2024 Justin Ridgewell <justin@ridgewell.name>"},
    {name: "@jridgewell/remapping", version: "2.3.5", licence: "MIT", copyright: "Copyright 2024 Justin Ridgewell <justin@ridgewell.name>"},
    {name: "@jridgewell/resolve-uri", version: "3.1.2", licence: "MIT", copyright: "Copyright 2019 Justin Ridgewell <jridgewell@google.com>"},
    {name: "@jridgewell/source-map", version: "0.3.11", licence: "MIT", copyright: "Copyright 2024 Justin Ridgewell <justin@ridgewell.name>"},
    {name: "@jridgewell/sourcemap-codec", version: "1.5.5", licence: "MIT", copyright: "Copyright 2024 Justin Ridgewell <justin@ridgewell.name>"},
    {name: "@jridgewell/trace-mapping", version: "0.3.31", licence: "MIT", copyright: "Copyright 2024 Justin Ridgewell <justin@ridgewell.name>"},
    {name: "@miblanchard/react-native-slider", version: "2.6.0", licence: "MIT"},
    {name: "@radix-ui/primitive", version: "1.1.7", licence: "MIT", copyright: "Copyright (c) 2022 WorkOS"},
    {name: "@radix-ui/react-collection", version: "1.1.15", licence: "MIT", copyright: "Copyright (c) 2022 WorkOS"},
    {name: "@radix-ui/react-compose-refs", version: "1.1.5", licence: "MIT", copyright: "Copyright (c) 2022 WorkOS"},
    {name: "@radix-ui/react-context", version: "1.2.2", licence: "MIT", copyright: "Copyright (c) 2022 WorkOS"},
    {name: "@radix-ui/react-dialog", version: "1.1.23", licence: "MIT", copyright: "Copyright (c) 2022 WorkOS"},
    {name: "@radix-ui/react-direction", version: "1.1.4", licence: "MIT", copyright: "Copyright (c) 2022 WorkOS"},
    {name: "@radix-ui/react-dismissable-layer", version: "1.1.19", licence: "MIT", copyright: "Copyright (c) 2022 WorkOS"},
    {name: "@radix-ui/react-focus-guards", version: "1.1.6", licence: "MIT", copyright: "Copyright (c) 2022 WorkOS"},
    {name: "@radix-ui/react-focus-scope", version: "1.1.16", licence: "MIT", copyright: "Copyright (c) 2022 WorkOS"},
    {name: "@radix-ui/react-id", version: "1.1.4", licence: "MIT", copyright: "Copyright (c) 2022 WorkOS"},
    {name: "@radix-ui/react-portal", version: "1.1.17", licence: "MIT", copyright: "Copyright (c) 2022 WorkOS"},
    {name: "@radix-ui/react-presence", version: "1.1.10", licence: "MIT", copyright: "Copyright (c) 2022 WorkOS"},
    {name: "@radix-ui/react-primitive", version: "2.1.10", licence: "MIT", copyright: "Copyright (c) 2022 WorkOS"},
    {name: "@radix-ui/react-roving-focus", version: "1.1.19", licence: "MIT", copyright: "Copyright (c) 2022 WorkOS"},
    {name: "@radix-ui/react-slot", version: "1.3.3", licence: "MIT", copyright: "Copyright (c) 2022 WorkOS"},
    {name: "@radix-ui/react-tabs", version: "1.1.21", licence: "MIT", copyright: "Copyright (c) 2022 WorkOS"},
    {name: "@radix-ui/react-use-callback-ref", version: "1.1.4", licence: "MIT", copyright: "Copyright (c) 2022 WorkOS"},
    {name: "@radix-ui/react-use-controllable-state", version: "1.2.6", licence: "MIT", copyright: "Copyright (c) 2022 WorkOS"},
    {name: "@radix-ui/react-use-effect-event", version: "0.0.5", licence: "MIT", copyright: "Copyright (c) 2022 WorkOS"},
    {name: "@radix-ui/react-use-is-hydrated", version: "0.1.3", licence: "MIT", copyright: "Copyright (c) 2022 WorkOS"},
    {name: "@radix-ui/react-use-layout-effect", version: "1.1.4", licence: "MIT", copyright: "Copyright (c) 2022 WorkOS"},
    {name: "@react-native-masked-view/masked-view", version: "0.3.2", licence: "MIT"},
    {name: "@react-native/assets-registry", version: "0.86.2", licence: "MIT"},
    {name: "@react-native/babel-plugin-codegen", version: "0.86.2", licence: "MIT"},
    {name: "@react-native/babel-preset", version: "0.86.2", licence: "MIT"},
    {name: "@react-native/codegen", version: "0.86.2", licence: "MIT"},
    {name: "@react-native/community-cli-plugin", version: "0.86.2", licence: "MIT"},
    {name: "@react-native/debugger-frontend", version: "0.86.2", licence: "BSD-3-Clause"},
    {name: "@react-native/debugger-shell", version: "0.86.2", licence: "MIT"},
    {name: "@react-native/dev-middleware", version: "0.86.2", licence: "MIT"},
    {name: "@react-native/gradle-plugin", version: "0.86.2", licence: "MIT"},
    {name: "@react-native/jest-preset", version: "0.86.2", licence: "MIT"},
    {name: "@react-native/js-polyfills", version: "0.86.2", licence: "MIT"},
    {name: "@react-native/metro-babel-transformer", version: "0.86.2", licence: "MIT"},
    {name: "@react-native/metro-config", version: "0.86.2", licence: "MIT"},
    {name: "@react-native/normalize-color", version: "2.1.0", licence: "MIT"},
    {name: "@react-native/normalize-colors", version: "0.83.2, 0.86.2", licence: "MIT"},
    {name: "@react-native/virtualized-lists", version: "0.86.2", licence: "MIT"},
    {name: "@sinclair/typebox", version: "0.27.12, 0.34.52", licence: "MIT"},
    {name: "@sinonjs/commons", version: "3.0.1", licence: "BSD-3-Clause", copyright: "Copyright (c) 2018, Sinon.JS"},
    {name: "@sinonjs/fake-timers", version: "10.3.0", licence: "BSD-3-Clause", copyright: "Copyright (c) 2010-2014, Christian Johansen, christian@cjohansen.no. All rights reserved."},
    {name: "@tamagui/accordion", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2021 Radix"},
    {name: "@tamagui/adapt", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/alert-dialog", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2022 WorkOS"},
    {name: "@tamagui/animate", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/animate-presence", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/animation-helpers", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/animations-css", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/animations-motion", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/animations-react-native", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/animations-reanimated", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/avatar", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/button", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/card", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/checkbox", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2021 Radix"},
    {name: "@tamagui/checkbox-headless", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2021 Radix"},
    {name: "@tamagui/collapsible", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2021 Radix"},
    {name: "@tamagui/collection", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2021 Radix"},
    {name: "@tamagui/colors", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2021 Radix"},
    {name: "@tamagui/compose-refs", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/config", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/config-default", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/constants", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/context-menu", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/core", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/create-context", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/create-menu", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/create-theme", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/cubic-bezier-animator", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2021 Radix"},
    {name: "@tamagui/dialog", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2022 WorkOS"},
    {name: "@tamagui/dismissable", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/element", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/elements", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/fake-react-native", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/floating", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/focus-guard", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/focus-scope", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/focusable", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/font-inter", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/font-silkscreen", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/font-size", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/form", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/get-button-sized", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/get-font-sized", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/get-token", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/group", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/helpers", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/helpers-tamagui", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/image", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/input", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/is-equal-shallow", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2025 Nate Wienert"},
    {name: "@tamagui/label", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/linear-gradient", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/list-item", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/menu", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/native", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/normalize-css-color", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/polyfill-dev", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/popover", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/popper", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/portal", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/progress", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/radio-group", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/radio-headless", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2021 Radix"},
    {name: "@tamagui/react-native-media-driver", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/react-native-use-pressable", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/remove-scroll", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/roving-focus", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2021 Radix"},
    {name: "@tamagui/scroll-view", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/select", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/separator", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/shapes", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/sheet", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/shorthands", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/simple-hash", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/sizable-context", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/slider", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/spacer", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/spinner", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/stacks", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/start-transition", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/switch", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/switch-headless", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/tabs", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2021 Radix"},
    {name: "@tamagui/text", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/theme", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/theme-builder", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/themes", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/timer", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/toast", version: "2.7.7", licence: "See package"},
    {name: "@tamagui/toggle-group", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/tooltip", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/types", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/use-async", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2025 Tamagui"},
    {name: "@tamagui/use-callback-ref", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/use-constant", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/use-controllable-state", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/use-debounce", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/use-did-finish-ssr", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/use-direction", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/use-element-layout", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/use-escape-keydown", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2021 Radix"},
    {name: "@tamagui/use-event", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/use-force-update", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/use-keyboard-visible", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/use-presence", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/use-previous", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/use-window-dimensions", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/visually-hidden", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/web", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@tamagui/z-index-stack", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "@testing-library/react-native", version: "14.0.1", licence: "MIT", copyright: "Copyright (c) 2018 Callstack and Rally Health"},
    {name: "@types/babel__core", version: "7.20.5", licence: "MIT"},
    {name: "@types/babel__generator", version: "7.27.0", licence: "MIT"},
    {name: "@types/babel__template", version: "7.4.4", licence: "MIT"},
    {name: "@types/babel__traverse", version: "7.28.0", licence: "MIT"},
    {name: "@types/graceful-fs", version: "4.1.9", licence: "MIT"},
    {name: "@types/hammerjs", version: "2.0.46", licence: "MIT"},
    {name: "@types/istanbul-lib-coverage", version: "2.0.6", licence: "MIT"},
    {name: "@types/istanbul-lib-report", version: "3.0.3", licence: "MIT"},
    {name: "@types/istanbul-reports", version: "3.0.4", licence: "MIT"},
    {name: "@types/node", version: "26.2.0", licence: "MIT"},
    {name: "@types/react", version: "19.2.18", licence: "MIT"},
    {name: "@types/react-reconciler", version: "0.33.0", licence: "MIT"},
    {name: "@types/react-test-renderer", version: "19.1.0", licence: "MIT"},
    {name: "@types/stack-utils", version: "2.0.3", licence: "MIT"},
    {name: "@types/yargs", version: "17.0.35", licence: "MIT"},
    {name: "@types/yargs-parser", version: "21.0.3", licence: "MIT"},
    {name: "@ungap/structured-clone", version: "1.3.3", licence: "ISC", copyright: "Copyright (c) 2021, Andrea Giammarchi, @WebReflection"},
    {name: "@xmldom/xmldom", version: "0.8.14, 0.9.11", licence: "MIT", copyright: "Copyright 2019 - present Christopher J. Brody and other contributors, as listed in: https://github.com/xmldom/xmldom/graphs/contributors"},
    {name: "@yarnpkg/lockfile", version: "1.1.0", licence: "BSD-2-Clause"},
    {name: "abort-controller", version: "3.0.0", licence: "MIT", copyright: "Copyright (c) 2017 Toru Nagashima"},
    {name: "accepts", version: "1.3.8, 2.0.0", licence: "MIT", copyright: "Copyright (c) 2014 Jonathan Ong <me@jongleberry.com>"},
    {name: "acorn", version: "8.18.0", licence: "MIT", copyright: "Copyright (C) 2012-2022 by various contributors (see AUTHORS)"},
    {name: "agent-base", version: "7.1.4", licence: "MIT", copyright: "Copyright (c) 2013 Nathan Rajlich <nathan@tootallnate.net>"},
    {name: "agent-cli-detector", version: "0.1.6", licence: "MIT", copyright: "Copyright (c) 2026 David Mokos"},
    {name: "anser", version: "1.4.10", licence: "MIT", copyright: "Copyright (c) 2012-20 Ionic\u0103 Biz\u0103u <bizauionica@gmail.com> (https://ionicabizau.net)"},
    {name: "ansi-escapes", version: "4.3.2", licence: "MIT"},
    {name: "ansi-regex", version: "4.1.1, 5.0.1", licence: "MIT"},
    {name: "ansi-styles", version: "3.2.1, 4.3.0, 5.2.0", licence: "MIT"},
    {name: "anymatch", version: "3.1.3", licence: "ISC", copyright: "Copyright (c) 2019 Elan Shanker, Paul Miller (https://paulmillr.com)"},
    {name: "arg", version: "5.0.2", licence: "MIT", copyright: "Copyright (c) 2021 Vercel, Inc."},
    {name: "argparse", version: "1.0.10, 2.0.1", licence: "MIT / Python-2.0", copyright: "Copyright (C) 2012 by Vitaly Puzrin; Copyright (c) 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,"},
    {name: "aria-hidden", version: "1.2.6", licence: "MIT", copyright: "Copyright (c) 2017 Anton Korzunov"},
    {name: "asap", version: "2.0.6", licence: "MIT", copyright: "Copyright 2009\u20132014 Contributors. All rights reserved."},
    {name: "await-lock", version: "2.2.2", licence: "MIT"},
    {name: "babel-jest", version: "29.7.0", licence: "MIT"},
    {name: "babel-plugin-istanbul", version: "6.1.1", licence: "BSD-3-Clause", copyright: "Copyright (c) 2016, Istanbul Code Coverage"},
    {name: "babel-plugin-jest-hoist", version: "29.6.3", licence: "MIT"},
    {name: "babel-plugin-polyfill-corejs2", version: "0.4.17", licence: "MIT"},
    {name: "babel-plugin-polyfill-corejs3", version: "0.13.0", licence: "MIT"},
    {name: "babel-plugin-polyfill-regenerator", version: "0.6.8", licence: "MIT"},
    {name: "babel-plugin-react-compiler", version: "1.0.0", licence: "MIT"},
    {name: "babel-plugin-react-native-web", version: "0.21.2", licence: "MIT"},
    {name: "babel-plugin-syntax-hermes-parser", version: "0.36.0, 0.36.1", licence: "MIT"},
    {name: "babel-plugin-transform-flow-enums", version: "0.0.2", licence: "MIT"},
    {name: "babel-preset-current-node-syntax", version: "1.2.0", licence: "MIT", copyright: "Copyright (c) 2020 Nicol\u00f2 Ribaudo and other contributors"},
    {name: "babel-preset-expo", version: "57.0.8", licence: "MIT"},
    {name: "babel-preset-jest", version: "29.6.3", licence: "MIT"},
    {name: "balanced-match", version: "1.0.2, 4.0.4", licence: "MIT", copyright: "Copyright (c) 2013 Julian Gruber &lt;julian@juliangruber.com&gt;"},
    {name: "base64-js", version: "1.5.1", licence: "MIT", copyright: "Copyright (c) 2014 Jameson Little"},
    {name: "baseline-browser-mapping", version: "2.11.16", licence: "Apache-2.0"},
    {name: "big-integer", version: "1.6.52", licence: "Unlicense"},
    {name: "boolbase", version: "1.0.0", licence: "ISC"},
    {name: "bplist-creator", version: "0.1.0", licence: "MIT", copyright: "Copyright (c) 2012 Near Infinity Corporation"},
    {name: "bplist-parser", version: "0.3.1", licence: "MIT"},
    {name: "brace-expansion", version: "1.1.18, 5.0.9", licence: "MIT", copyright: "Copyright (c) 2013 Julian Gruber <julian@juliangruber.com>"},
    {name: "braces", version: "3.0.3", licence: "MIT"},
    {name: "browserslist", version: "4.28.8", licence: "MIT", copyright: "Copyright 2014 Andrey Sitnik <andrey@sitnik.es> and other contributors"},
    {name: "bser", version: "2.1.1", licence: "Apache-2.0"},
    {name: "buffer", version: "6.0.3", licence: "MIT"},
    {name: "buffer-from", version: "1.1.2", licence: "MIT", copyright: "Copyright (c) 2016, 2018 Linus Unneb\u00e4ck"},
    {name: "bytes", version: "3.1.2", licence: "MIT", copyright: "Copyright (c) 2012-2014 TJ Holowaychuk <tj@vision-media.ca>"},
    {name: "call-bind", version: "1.0.9", licence: "MIT", copyright: "Copyright (c) 2020 Jordan Harband"},
    {name: "call-bind-apply-helpers", version: "1.0.2", licence: "MIT", copyright: "Copyright (c) 2024 Jordan Harband"},
    {name: "call-bound", version: "1.0.4", licence: "MIT", copyright: "Copyright (c) 2024 Jordan Harband"},
    {name: "callsites", version: "3.1.0", licence: "MIT"},
    {name: "camelcase", version: "5.3.1, 6.3.0", licence: "MIT"},
    {name: "caniuse-lite", version: "1.0.30001809", licence: "CC-BY-4.0"},
    {name: "chalk", version: "2.4.2, 4.1.2", licence: "MIT"},
    {name: "char-regex", version: "1.0.2", licence: "MIT", copyright: "Copyright (c) 2019 Richie Bendall"},
    {name: "chrome-launcher", version: "0.15.2", licence: "Apache-2.0", copyright: "Copyright 2014 Google Inc."},
    {name: "chromium-edge-launcher", version: "0.3.0", licence: "Apache-2.0", copyright: "Copyright 2014 Google Inc."},
    {name: "ci-info", version: "2.0.0, 3.9.0", licence: "MIT", copyright: "Copyright (c) 2016 Thomas Watson Steen; Copyright (c) 2016-2018 Thomas Watson Steen"},
    {name: "cjs-module-lexer", version: "1.4.3", licence: "MIT", copyright: "Copyright (C) 2018-2020 Guy Bedford"},
    {name: "cli-cursor", version: "2.1.0", licence: "MIT"},
    {name: "cli-spinners", version: "2.9.2", licence: "MIT"},
    {name: "client-only", version: "0.0.1", licence: "MIT"},
    {name: "cliui", version: "8.0.1", licence: "ISC", copyright: "Copyright (c) 2015, Contributors"},
    {name: "clone", version: "1.0.4", licence: "MIT", copyright: "Copyright \u00a9 2011-2015 Paul Vorbach <paul@vorba.ch>"},
    {name: "co", version: "4.6.0", licence: "MIT", copyright: "Copyright (c) 2014 TJ Holowaychuk &lt;tj@vision-media.ca&gt;"},
    {name: "collect-v8-coverage", version: "1.0.3", licence: "MIT", copyright: "Copyright (c) 2019 Simen Bekkhus"},
    {name: "color", version: "4.2.3", licence: "MIT", copyright: "Copyright (c) 2012 Heather Arthur"},
    {name: "color-convert", version: "1.9.3, 2.0.1", licence: "MIT", copyright: "Copyright (c) 2011-2016 Heather Arthur <fayearthur@gmail.com>"},
    {name: "color-name", version: "1.1.3, 1.1.4", licence: "MIT", copyright: "Copyright (c) 2015 Dmitry Ivanov"},
    {name: "color-string", version: "1.9.1", licence: "MIT", copyright: "Copyright (c) 2011 Heather Arthur <fayearthur@gmail.com>"},
    {name: "color2k", version: "2.0.4", licence: "MIT", copyright: "Copyright (c) 2020 Rico Kahler"},
    {name: "commander", version: "12.1.0, 2.20.3, 7.2.0", licence: "MIT", copyright: "Copyright (c) 2011 TJ Holowaychuk <tj@vision-media.ca>"},
    {name: "compressible", version: "2.0.18", licence: "MIT", copyright: "Copyright (c) 2013 Jonathan Ong <me@jongleberry.com>"},
    {name: "compression", version: "1.8.1", licence: "MIT", copyright: "Copyright (c) 2014 Jonathan Ong <me@jongleberry.com>"},
    {name: "concat-map", version: "0.0.1", licence: "MIT"},
    {name: "connect", version: "3.7.0", licence: "MIT", copyright: "Copyright (c) 2010 Sencha Inc."},
    {name: "content-type", version: "2.1.0", licence: "MIT", copyright: "Copyright (c) 2015 Douglas Christopher Wilson"},
    {name: "convert-source-map", version: "2.0.0", licence: "MIT", copyright: "Copyright 2013 Thorsten Lorenz."},
    {name: "core-js-compat", version: "3.50.0", licence: "MIT", copyright: "Copyright (c) 2013\u20132025 Denis Pushkarev (zloirock.ru)"},
    {name: "create-jest", version: "29.7.0", licence: "MIT"},
    {name: "cross-spawn", version: "7.0.6", licence: "MIT", copyright: "Copyright (c) 2018 Made With MOXY Lda <hello@moxy.studio>"},
    {name: "css-select", version: "5.2.2", licence: "BSD-2-Clause"},
    {name: "css-tree", version: "1.1.3", licence: "MIT", copyright: "Copyright (C) 2016-2019 by Roman Dvornov"},
    {name: "css-what", version: "6.2.2", licence: "BSD-2-Clause"},
    {name: "csstype", version: "3.2.3", licence: "MIT", copyright: "Copyright (c) 2017-2018 Fredrik Nicol"},
    {name: "debug", version: "2.6.9, 3.2.7, 4.4.3", licence: "MIT", copyright: "Copyright (c) 2014 TJ Holowaychuk <tj@vision-media.ca>; Copyright (c) 2014-2017 TJ Holowaychuk <tj@vision-media.ca>"},
    {name: "decode-uri-component", version: "0.2.2", licence: "MIT"},
    {name: "dedent", version: "1.7.2", licence: "MIT"},
    {name: "deepmerge", version: "4.3.1", licence: "MIT"},
    {name: "defaults", version: "1.0.4", licence: "MIT", copyright: "Copyright (c) 2022 Sindre Sorhus"},
    {name: "define-data-property", version: "1.1.4", licence: "MIT", copyright: "Copyright (c) 2023 Jordan Harband"},
    {name: "depd", version: "2.0.0", licence: "MIT", copyright: "Copyright (c) 2014-2018 Douglas Christopher Wilson"},
    {name: "destroy", version: "1.2.0", licence: "MIT", copyright: "Copyright (c) 2014 Jonathan Ong me@jongleberry.com"},
    {name: "detect-libc", version: "2.1.2", licence: "Apache-2.0"},
    {name: "detect-newline", version: "3.1.0", licence: "MIT"},
    {name: "detect-node-es", version: "1.1.0", licence: "MIT", copyright: "Copyright (c) 2017 Ilya Kantor"},
    {name: "diff-sequences", version: "29.6.3", licence: "MIT"},
    {name: "dnssd-advertise", version: "1.1.6", licence: "MIT", copyright: "Copyright (c) 650 Industries, Inc. (aka Expo),"},
    {name: "dom-serializer", version: "2.0.0", licence: "MIT", copyright: "Copyright (c) 2014 The cheeriojs contributors"},
    {name: "domelementtype", version: "2.3.0", licence: "BSD-2-Clause"},
    {name: "domhandler", version: "5.0.3", licence: "BSD-2-Clause"},
    {name: "domutils", version: "3.2.2", licence: "BSD-2-Clause"},
    {name: "dunder-proto", version: "1.0.1", licence: "MIT", copyright: "Copyright (c) 2024 ECMAScript Shims"},
    {name: "ee-first", version: "1.1.1", licence: "MIT", copyright: "Copyright (c) 2014 Jonathan Ong me@jongleberry.com"},
    {name: "electron-to-chromium", version: "1.5.412", licence: "ISC", copyright: "Copyright 2018 Kilian Valkhof"},
    {name: "emittery", version: "0.13.1", licence: "MIT"},
    {name: "emoji-regex", version: "8.0.0", licence: "MIT"},
    {name: "encodeurl", version: "1.0.2, 2.0.0", licence: "MIT", copyright: "Copyright (c) 2016 Douglas Christopher Wilson"},
    {name: "entities", version: "4.5.0", licence: "BSD-2-Clause"},
    {name: "error-ex", version: "1.3.4", licence: "MIT", copyright: "Copyright (c) 2015 JD Ballard"},
    {name: "error-stack-parser", version: "2.1.4", licence: "MIT", copyright: "Copyright (c) 2017 Eric Wendelin and other contributors"},
    {name: "es-define-property", version: "1.0.1", licence: "MIT", copyright: "Copyright (c) 2024 Jordan Harband"},
    {name: "es-errors", version: "1.3.0", licence: "MIT", copyright: "Copyright (c) 2024 Jordan Harband"},
    {name: "es-object-atoms", version: "1.1.2", licence: "MIT", copyright: "Copyright (c) 2024 Jordan Harband"},
    {name: "escalade", version: "3.2.0", licence: "MIT"},
    {name: "escape-html", version: "1.0.3", licence: "MIT", copyright: "Copyright (c) 2012-2013 TJ Holowaychuk"},
    {name: "escape-string-regexp", version: "1.0.5, 2.0.0, 4.0.0", licence: "MIT"},
    {name: "esprima", version: "4.0.1", licence: "BSD-2-Clause"},
    {name: "etag", version: "1.8.1", licence: "MIT", copyright: "Copyright (c) 2014-2016 Douglas Christopher Wilson"},
    {name: "event-target-shim", version: "5.0.1", licence: "MIT", copyright: "Copyright (c) 2015 Toru Nagashima"},
    {name: "execa", version: "5.1.1", licence: "MIT"},
    {name: "exit", version: "0.1.2", licence: "MIT", copyright: "Copyright (c) 2013 \"Cowboy\" Ben Alman"},
    {name: "expect", version: "29.7.0", licence: "MIT"},
    {name: "expo", version: "57.0.16", licence: "MIT"},
    {name: "expo-asset", version: "57.0.14", licence: "MIT"},
    {name: "expo-build-properties", version: "57.0.14", licence: "MIT"},
    {name: "expo-clipboard", version: "57.0.1", licence: "MIT"},
    {name: "expo-constants", version: "57.0.14", licence: "MIT"},
    {name: "expo-dev-client", version: "57.0.15", licence: "MIT"},
    {name: "expo-dev-launcher", version: "57.0.15", licence: "MIT"},
    {name: "expo-dev-menu", version: "57.0.15", licence: "MIT"},
    {name: "expo-dev-menu-interface", version: "57.0.0", licence: "MIT"},
    {name: "expo-file-system", version: "57.0.5", licence: "MIT"},
    {name: "expo-font", version: "57.0.1", licence: "MIT"},
    {name: "expo-glass-effect", version: "57.0.1", licence: "MIT"},
    {name: "expo-json-utils", version: "57.0.1", licence: "MIT"},
    {name: "expo-keep-awake", version: "57.0.1", licence: "MIT"},
    {name: "expo-linking", version: "57.0.7", licence: "MIT"},
    {name: "expo-manifests", version: "57.0.1", licence: "MIT"},
    {name: "expo-modules-autolinking", version: "57.0.11", licence: "MIT"},
    {name: "expo-modules-core", version: "57.0.13", licence: "MIT"},
    {name: "expo-modules-jsi", version: "57.0.5", licence: "MIT"},
    {name: "expo-router", version: "57.0.16", licence: "MIT"},
    {name: "expo-server", version: "57.0.3", licence: "MIT"},
    {name: "expo-share-intent", version: "8.0.1", licence: "MIT", copyright: "Copyright (c) 2023 Evan Bacon"},
    {name: "expo-splash-screen", version: "57.0.8", licence: "MIT"},
    {name: "expo-sqlite", version: "57.0.1", licence: "MIT"},
    {name: "expo-status-bar", version: "57.0.1", licence: "MIT"},
    {name: "expo-symbols", version: "57.0.2", licence: "MIT"},
    {name: "expo-system-ui", version: "57.0.2", licence: "MIT"},
    {name: "expo-updates-interface", version: "57.0.1", licence: "MIT"},
    {name: "exponential-backoff", version: "3.1.3", licence: "Apache-2.0", copyright: "Copyright 2019 Coveo Solutions Inc."},
    {name: "fast-deep-equal", version: "3.1.3", licence: "MIT", copyright: "Copyright (c) 2017 Evgeny Poberezkin"},
    {name: "fast-json-stable-stringify", version: "2.1.0", licence: "MIT", copyright: "Copyright (c) 2017 Evgeny Poberezkin"},
    {name: "fb-dotslash", version: "0.5.8", licence: "(MIT OR Apache-2.0)"},
    {name: "fb-watchman", version: "2.0.2", licence: "Apache-2.0"},
    {name: "fdir", version: "6.5.0", licence: "MIT", copyright: "Copyright 2023 Abdullah Atta"},
    {name: "fetch-nodeshim", version: "0.4.10", licence: "MIT", copyright: "Copyright (c) 650 Industries, Inc. (aka Expo),"},
    {name: "fill-range", version: "7.1.1", licence: "MIT"},
    {name: "filter-obj", version: "1.1.0", licence: "MIT"},
    {name: "finalhandler", version: "1.1.2", licence: "MIT", copyright: "Copyright (c) 2014-2017 Douglas Christopher Wilson <doug@somethingdoug.com>"},
    {name: "find-up", version: "4.1.0", licence: "MIT"},
    {name: "find-yarn-workspace-root", version: "2.0.0", licence: "Apache-2.0", copyright: "Copyright 2017 Square, Inc."},
    {name: "flow-enums-runtime", version: "0.0.6", licence: "MIT"},
    {name: "fontfaceobserver", version: "2.3.0", licence: "BSD-2-Clause", copyright: "Copyright (c) 2014 - Bram Stein"},
    {name: "framer-motion", version: "13.1.1", licence: "MIT", copyright: "Copyright (c) 2018 Framer B.V."},
    {name: "fresh", version: "0.5.2", licence: "MIT", copyright: "Copyright (c) 2012 TJ Holowaychuk <tj@vision-media.ca>"},
    {name: "fs-extra", version: "10.1.0", licence: "MIT", copyright: "Copyright (c) 2011-2017 JP Richardson"},
    {name: "fs.realpath", version: "1.0.0", licence: "ISC"},
    {name: "fsevents", version: "2.3.3", licence: "MIT", copyright: "Copyright (C) 2010-2020 by Philipp Dunkel, Ben Noordhuis, Elan Shankar, Paul Miller"},
    {name: "function-bind", version: "1.1.2", licence: "MIT", copyright: "Copyright (c) 2013 Raynos."},
    {name: "gensync", version: "1.0.0-beta.2", licence: "MIT", copyright: "Copyright 2018 Logan Smyth <loganfsmyth@gmail.com>"},
    {name: "get-caller-file", version: "2.0.5", licence: "ISC", copyright: "Copyright 2018 Stefan Penner"},
    {name: "get-intrinsic", version: "1.3.0", licence: "MIT", copyright: "Copyright (c) 2020 Jordan Harband"},
    {name: "get-nonce", version: "1.0.1", licence: "MIT", copyright: "Copyright (c) 2020 Anton Korzunov"},
    {name: "get-package-type", version: "0.1.0", licence: "MIT", copyright: "Copyright (c) 2020 CFWare, LLC"},
    {name: "get-proto", version: "1.0.1", licence: "MIT", copyright: "Copyright (c) 2025 Jordan Harband"},
    {name: "get-stream", version: "6.0.1", licence: "MIT"},
    {name: "getenv", version: "2.0.0", licence: "MIT", copyright: "Copyright (c) 2012-2019 Christoph Tavan <dev@tavan.de>"},
    {name: "glob", version: "13.0.6, 7.2.3", licence: "BlueOak-1.0.0 / ISC"},
    {name: "gopd", version: "1.2.0", licence: "MIT", copyright: "Copyright (c) 2022 Jordan Harband"},
    {name: "graceful-fs", version: "4.2.11", licence: "ISC", copyright: "Copyright (c) 2011-2022 Isaac Z. Schlueter, Ben Noordhuis, and Contributors"},
    {name: "has-flag", version: "3.0.0, 4.0.0", licence: "MIT"},
    {name: "has-property-descriptors", version: "1.0.2", licence: "MIT", copyright: "Copyright (c) 2022 Inspect JS"},
    {name: "has-symbols", version: "1.1.0", licence: "MIT", copyright: "Copyright (c) 2016 Jordan Harband"},
    {name: "hasown", version: "2.0.4", licence: "MIT"},
    {name: "hermes-compiler", version: "250829098.0.16", licence: "MIT"},
    {name: "hermes-estree", version: "0.35.0, 0.36.0, 0.36.1", licence: "MIT"},
    {name: "hermes-parser", version: "0.35.0, 0.36.0, 0.36.1", licence: "MIT"},
    {name: "hoist-non-react-statics", version: "3.3.2", licence: "BSD-3-Clause", copyright: "Copyright (c) 2015, Yahoo! Inc. All rights reserved."},
    {name: "hosted-git-info", version: "7.0.2", licence: "ISC", copyright: "Copyright (c) 2015, Rebecca Turner"},
    {name: "html-escaper", version: "2.0.2", licence: "MIT"},
    {name: "http-errors", version: "2.0.1", licence: "MIT", copyright: "Copyright (c) 2014 Jonathan Ong me@jongleberry.com"},
    {name: "https-proxy-agent", version: "7.0.6", licence: "MIT", copyright: "Copyright (c) 2013 Nathan Rajlich <nathan@tootallnate.net>"},
    {name: "human-signals", version: "2.1.0", licence: "Apache-2.0", copyright: "Copyright 2019 ehmicky <ehmicky@gmail.com>"},
    {name: "ieee754", version: "1.2.1", licence: "BSD-3-Clause", copyright: "Copyright 2008 Fair Oaks Labs, Inc."},
    {name: "ignore", version: "5.3.2", licence: "MIT", copyright: "Copyright (c) 2013 Kael Zhang <i@kael.me>, contributors"},
    {name: "import-local", version: "3.2.0", licence: "MIT"},
    {name: "imurmurhash", version: "0.1.4", licence: "MIT"},
    {name: "indent-string", version: "4.0.0", licence: "MIT"},
    {name: "inflight", version: "1.0.6", licence: "ISC"},
    {name: "inherits", version: "2.0.4", licence: "ISC"},
    {name: "invariant", version: "2.2.4", licence: "MIT"},
    {name: "is-arrayish", version: "0.2.1, 0.3.4", licence: "MIT", copyright: "Copyright (c) 2015 JD Ballard"},
    {name: "is-core-module", version: "2.16.2", licence: "MIT", copyright: "Copyright (c) 2014 Dave Justice"},
    {name: "is-docker", version: "2.2.1", licence: "MIT"},
    {name: "is-fullwidth-code-point", version: "3.0.0", licence: "MIT"},
    {name: "is-generator-fn", version: "2.1.0", licence: "MIT"},
    {name: "is-number", version: "7.0.0", licence: "MIT"},
    {name: "is-stream", version: "2.0.1", licence: "MIT"},
    {name: "is-wsl", version: "2.2.0", licence: "MIT"},
    {name: "isarray", version: "2.0.5", licence: "MIT", copyright: "Copyright (c) 2013 Julian Gruber <julian@juliangruber.com>"},
    {name: "isexe", version: "2.0.0", licence: "ISC"},
    {name: "istanbul-lib-coverage", version: "3.2.2", licence: "BSD-3-Clause", copyright: "Copyright 2012-2015 Yahoo! Inc."},
    {name: "istanbul-lib-instrument", version: "5.2.1, 6.0.3", licence: "BSD-3-Clause", copyright: "Copyright 2012-2015 Yahoo! Inc."},
    {name: "istanbul-lib-report", version: "3.0.1", licence: "BSD-3-Clause", copyright: "Copyright 2012-2015 Yahoo! Inc."},
    {name: "istanbul-lib-source-maps", version: "4.0.1", licence: "BSD-3-Clause", copyright: "Copyright 2015 Yahoo! Inc."},
    {name: "istanbul-reports", version: "3.2.0", licence: "BSD-3-Clause", copyright: "Copyright 2012-2015 Yahoo! Inc."},
    {name: "jest", version: "29.7.0", licence: "MIT"},
    {name: "jest-changed-files", version: "29.7.0", licence: "MIT"},
    {name: "jest-circus", version: "29.7.0", licence: "MIT"},
    {name: "jest-cli", version: "29.7.0", licence: "MIT"},
    {name: "jest-config", version: "29.7.0", licence: "MIT"},
    {name: "jest-diff", version: "29.7.0, 30.4.1", licence: "MIT"},
    {name: "jest-docblock", version: "29.7.0", licence: "MIT"},
    {name: "jest-each", version: "29.7.0", licence: "MIT"},
    {name: "jest-environment-node", version: "29.7.0", licence: "MIT"},
    {name: "jest-get-type", version: "29.6.3", licence: "MIT"},
    {name: "jest-haste-map", version: "29.7.0", licence: "MIT"},
    {name: "jest-leak-detector", version: "29.7.0", licence: "MIT"},
    {name: "jest-matcher-utils", version: "29.7.0, 30.4.1", licence: "MIT"},
    {name: "jest-message-util", version: "29.7.0", licence: "MIT"},
    {name: "jest-mock", version: "29.7.0", licence: "MIT"},
    {name: "jest-pnp-resolver", version: "1.2.3", licence: "MIT"},
    {name: "jest-regex-util", version: "29.6.3", licence: "MIT"},
    {name: "jest-resolve", version: "29.7.0", licence: "MIT"},
    {name: "jest-resolve-dependencies", version: "29.7.0", licence: "MIT"},
    {name: "jest-runner", version: "29.7.0", licence: "MIT"},
    {name: "jest-runtime", version: "29.7.0", licence: "MIT"},
    {name: "jest-snapshot", version: "29.7.0", licence: "MIT"},
    {name: "jest-util", version: "29.7.0", licence: "MIT"},
    {name: "jest-validate", version: "29.7.0", licence: "MIT"},
    {name: "jest-watcher", version: "29.7.0", licence: "MIT"},
    {name: "jest-worker", version: "29.7.0", licence: "MIT"},
    {name: "jimp-compact", version: "0.16.1", licence: "MIT"},
    {name: "js-tokens", version: "4.0.0", licence: "MIT", copyright: "Copyright (c) 2014, 2015, 2016, 2017, 2018 Simon Lydell"},
    {name: "js-yaml", version: "3.15.1, 4.3.1", licence: "MIT", copyright: "Copyright (C) 2011-2015 by Vitaly Puzrin"},
    {name: "jsc-safe-url", version: "0.2.4", licence: "0BSD"},
    {name: "jsesc", version: "3.1.0", licence: "MIT"},
    {name: "json-parse-even-better-errors", version: "2.3.1", licence: "MIT", copyright: "Copyright 2017 Kat March\u00e1n"},
    {name: "json-stable-stringify", version: "1.3.0", licence: "MIT", copyright: "Copyright (c) 2013 contributors"},
    {name: "json5", version: "2.2.3", licence: "MIT", copyright: "Copyright (c) 2012-2018 Aseem Kishore, and [others]."},
    {name: "jsonfile", version: "6.2.1", licence: "MIT", copyright: "Copyright (c) 2012-2015, JP Richardson <jprichardson@gmail.com>"},
    {name: "jsonify", version: "0.0.1", licence: "Public Domain"},
    {name: "klaw-sync", version: "6.0.0", licence: "MIT", copyright: "Copyright (c) 2017 Mani Maghsoudlou"},
    {name: "kleur", version: "3.0.3", licence: "MIT"},
    {name: "lan-network", version: "0.2.1", licence: "MIT"},
    {name: "leven", version: "3.1.0", licence: "MIT"},
    {name: "lighthouse-logger", version: "1.4.2", licence: "Apache-2.0", copyright: "Copyright 2014 Google Inc."},
    {name: "lightningcss", version: "1.33.0", licence: "MPL-2.0"},
    {name: "lightningcss-darwin-arm64", version: "1.33.0", licence: "MPL-2.0"},
    {name: "lines-and-columns", version: "1.2.4", licence: "MIT", copyright: "Copyright (c) 2015 Brian Donovan"},
    {name: "locate-path", version: "5.0.0", licence: "MIT"},
    {name: "lodash.debounce", version: "4.0.8", licence: "MIT"},
    {name: "lodash.throttle", version: "4.1.1", licence: "MIT"},
    {name: "log-symbols", version: "2.2.0", licence: "MIT"},
    {name: "loose-envify", version: "1.4.0", licence: "MIT", copyright: "Copyright (c) 2015 Andres Suarez <zertosh@gmail.com>"},
    {name: "lru-cache", version: "10.4.3, 11.5.2, 5.1.1", licence: "BlueOak-1.0.0 / ISC", copyright: "Copyright (c) 2010-2023 Isaac Z. Schlueter and Contributors"},
    {name: "make-dir", version: "4.0.0", licence: "MIT"},
    {name: "makeerror", version: "1.0.12", licence: "BSD-3-Clause"},
    {name: "marky", version: "1.3.0", licence: "Apache-2.0", copyright: "Copyright 2016 Nolan Lawson"},
    {name: "math-intrinsics", version: "1.1.0", licence: "MIT", copyright: "Copyright (c) 2024 ECMAScript Shims"},
    {name: "mdn-data", version: "2.0.14", licence: "CC0-1.0"},
    {name: "memoize-one", version: "5.2.1", licence: "MIT", copyright: "Copyright (c) 2019 Alexander Reardon"},
    {name: "merge-stream", version: "2.0.0", licence: "MIT"},
    {name: "metro", version: "0.84.5", licence: "MIT"},
    {name: "metro-babel-transformer", version: "0.84.5", licence: "MIT"},
    {name: "metro-cache", version: "0.84.5", licence: "MIT"},
    {name: "metro-cache-key", version: "0.84.5", licence: "MIT"},
    {name: "metro-config", version: "0.84.5", licence: "MIT"},
    {name: "metro-core", version: "0.84.5", licence: "MIT"},
    {name: "metro-file-map", version: "0.84.5", licence: "MIT"},
    {name: "metro-minify-terser", version: "0.84.5", licence: "MIT"},
    {name: "metro-resolver", version: "0.84.5", licence: "MIT"},
    {name: "metro-runtime", version: "0.84.5", licence: "MIT"},
    {name: "metro-source-map", version: "0.84.5", licence: "MIT"},
    {name: "metro-symbolicate", version: "0.84.5", licence: "MIT"},
    {name: "metro-transform-plugins", version: "0.84.5", licence: "MIT"},
    {name: "metro-transform-worker", version: "0.84.5", licence: "MIT"},
    {name: "micromatch", version: "4.0.8", licence: "MIT"},
    {name: "mime", version: "1.6.0", licence: "MIT", copyright: "Copyright (c) 2010 Benjamin Thomas, Robert Kieffer"},
    {name: "mime-db", version: "1.52.0, 1.54.0", licence: "MIT", copyright: "Copyright (c) 2014 Jonathan Ong <me@jongleberry.com>"},
    {name: "mime-types", version: "2.1.35, 3.0.2", licence: "MIT", copyright: "Copyright (c) 2014 Jonathan Ong <me@jongleberry.com>"},
    {name: "mimic-fn", version: "1.2.0, 2.1.0", licence: "MIT"},
    {name: "min-indent", version: "1.0.1", licence: "MIT"},
    {name: "minimatch", version: "10.2.6, 3.1.5", licence: "BlueOak-1.0.0 / ISC"},
    {name: "minimist", version: "1.2.8", licence: "MIT"},
    {name: "minipass", version: "7.1.3", licence: "BlueOak-1.0.0"},
    {name: "mkdirp", version: "1.0.4", licence: "MIT"},
    {name: "motion", version: "13.1.1", licence: "MIT", copyright: "Copyright (c) 2024 [Motion](https://motion.dev) B.V."},
    {name: "motion-dom", version: "13.1.1", licence: "MIT", copyright: "Copyright (c) 2024 [Motion](https://motion.dev) B.V."},
    {name: "motion-utils", version: "13.0.0", licence: "MIT", copyright: "Copyright (c) 2024 [Motion](https://motion.dev) B.V."},
    {name: "ms", version: "2.0.0, 2.1.3", licence: "MIT"},
    {name: "multitars", version: "1.0.2", licence: "MIT", copyright: "Copyright (c) 650 Industries, Inc. (aka Expo),"},
    {name: "nanoid", version: "3.3.18", licence: "MIT", copyright: "Copyright 2017 Andrey Sitnik <andrey@sitnik.ru>"},
    {name: "natural-compare", version: "1.4.0", licence: "MIT"},
    {name: "negotiator", version: "0.6.3, 0.6.4, 1.1.0", licence: "MIT", copyright: "Copyright (c) 2012-2014 Federico Romero"},
    {name: "node-forge", version: "1.4.0", licence: "(BSD-3-Clause OR GPL-2.0)", copyright: "Copyright (c) 2010, Digital Bazaar, Inc."},
    {name: "node-int64", version: "0.4.0", licence: "MIT", copyright: "Copyright (c) 2014 Robert Kieffer"},
    {name: "node-releases", version: "2.0.53", licence: "MIT", copyright: "Copyright (c) 2017 Sergey Rubanov (https://github.com/chicoxyzzy)"},
    {name: "normalize-path", version: "3.0.0", licence: "MIT", copyright: "Copyright (c) 2014-2018, Jon Schlinkert."},
    {name: "npm-package-arg", version: "11.0.3", licence: "ISC"},
    {name: "npm-run-path", version: "4.0.1", licence: "MIT"},
    {name: "nth-check", version: "2.1.1", licence: "BSD-2-Clause"},
    {name: "nullthrows", version: "1.1.1", licence: "MIT", copyright: "Copyright (c) 2016 Andres Suarez"},
    {name: "ob1", version: "0.84.5", licence: "MIT"},
    {name: "object-keys", version: "1.1.1", licence: "MIT", copyright: "Copyright (C) 2013 Jordan Harband"},
    {name: "on-finished", version: "2.3.0, 2.4.1", licence: "MIT", copyright: "Copyright (c) 2013 Jonathan Ong <me@jongleberry.com>"},
    {name: "on-headers", version: "1.1.0", licence: "MIT", copyright: "Copyright (c) 2014 Douglas Christopher Wilson"},
    {name: "once", version: "1.4.0", licence: "ISC"},
    {name: "onetime", version: "2.0.1, 5.1.2", licence: "MIT"},
    {name: "open", version: "7.4.2", licence: "MIT"},
    {name: "ora", version: "3.4.0", licence: "MIT"},
    {name: "p-limit", version: "2.3.0, 3.1.0", licence: "MIT"},
    {name: "p-locate", version: "4.1.0", licence: "MIT"},
    {name: "p-try", version: "2.2.0", licence: "MIT"},
    {name: "parse-json", version: "5.2.0", licence: "MIT"},
    {name: "parse-png", version: "2.1.0", licence: "MIT"},
    {name: "parseurl", version: "1.3.3", licence: "MIT", copyright: "Copyright (c) 2014 Jonathan Ong <me@jongleberry.com>"},
    {name: "patch-package", version: "8.0.1", licence: "MIT"},
    {name: "path-exists", version: "4.0.0", licence: "MIT"},
    {name: "path-is-absolute", version: "1.0.1", licence: "MIT"},
    {name: "path-key", version: "3.1.1", licence: "MIT"},
    {name: "path-parse", version: "1.0.7", licence: "MIT", copyright: "Copyright (c) 2015 Javier Blanco"},
    {name: "path-scurry", version: "2.0.2", licence: "BlueOak-1.0.0"},
    {name: "picocolors", version: "1.1.1", licence: "ISC", copyright: "Copyright (c) 2021-2024 Oleksii Raspopov, Kostiantyn Denysov, Anton Verinov"},
    {name: "picomatch", version: "2.3.2, 4.0.5", licence: "MIT"},
    {name: "pirates", version: "4.0.7", licence: "MIT", copyright: "Copyright (c) 2016-2018 Ari Porad"},
    {name: "pkg-dir", version: "4.2.0", licence: "MIT"},
    {name: "plist", version: "3.1.1", licence: "MIT", copyright: "Copyright (c) 2010-2017 Nathan Rajlich <nathan@tootallnate.net>"},
    {name: "pngjs", version: "3.4.0", licence: "MIT", copyright: "Copyright (c) 2015 Luke Page & Original Contributors"},
    {name: "postcss", version: "8.5.26", licence: "MIT", copyright: "Copyright 2013 Andrey Sitnik <andrey@sitnik.es>"},
    {name: "pretty-format", version: "29.7.0, 30.4.1", licence: "MIT"},
    {name: "proc-log", version: "4.2.0", licence: "ISC"},
    {name: "progress", version: "2.0.3", licence: "MIT", copyright: "Copyright (c) 2017 TJ Holowaychuk <tj@vision-media.ca>"},
    {name: "promise", version: "8.3.0", licence: "MIT", copyright: "Copyright (c) 2014 Forbes Lindesay"},
    {name: "prompts", version: "2.4.2", licence: "MIT"},
    {name: "pure-rand", version: "6.1.0", licence: "MIT", copyright: "Copyright (c) 2018 Nicolas DUBIEN"},
    {name: "query-string", version: "7.1.3", licence: "MIT"},
    {name: "range-parser", version: "1.2.1", licence: "MIT", copyright: "Copyright (c) 2012-2014 TJ Holowaychuk <tj@vision-media.ca>"},
    {name: "react", version: "19.2.3", licence: "MIT"},
    {name: "react-devtools-core", version: "6.1.5", licence: "MIT"},
    {name: "react-dom", version: "19.2.3", licence: "MIT"},
    {name: "react-fast-compare", version: "3.2.2", licence: "MIT", copyright: "Copyright (c) 2018 Formidable Labs"},
    {name: "react-freeze", version: "1.0.4", licence: "MIT", copyright: "Copyright (c) 2021 Software Mansion"},
    {name: "react-is", version: "16.13.1, 18.3.1, 19.2.8", licence: "MIT"},
    {name: "react-is-18", version: "18.3.1", licence: "MIT"},
    {name: "react-is-19", version: "19.2.8", licence: "MIT"},
    {name: "react-native", version: "0.86.2", licence: "MIT"},
    {name: "react-native-drawer-layout", version: "4.2.10", licence: "MIT", copyright: "Copyright (c) 2017 React Native Community"},
    {name: "react-native-gesture-handler", version: "2.32.0", licence: "MIT", copyright: "Copyright (c) 2016 Software Mansion <swmansion.com>"},
    {name: "react-native-is-edge-to-edge", version: "1.3.1", licence: "MIT", copyright: "Copyright (c) 2024 Mathieu Acthernoene"},
    {name: "react-native-nfc-manager", version: "3.17.2", licence: "MIT"},
    {name: "react-native-reanimated", version: "4.5.1", licence: "MIT", copyright: "Copyright (c) 2016 Software Mansion <swmansion.com>"},
    {name: "react-native-safe-area-context", version: "5.7.0", licence: "MIT", copyright: "Copyright (c) 2019 Th3rd Wave"},
    {name: "react-native-screens", version: "4.26.2", licence: "MIT", copyright: "Copyright (c) 2018 Software Mansion <swmansion.com>"},
    {name: "react-native-svg", version: "15.15.4", licence: "MIT"},
    {name: "react-native-teleport", version: "1.1.13", licence: "MIT", copyright: "Copyright (c) 2025 Kiryl Ziusko"},
    {name: "react-native-uuid", version: "2.0.4", licence: "MIT", copyright: "Copyright (c) 2016-2021 Eugene Hauptmann"},
    {name: "react-native-worklets", version: "0.10.1", licence: "MIT", copyright: "Copyright (c) 2024 nobody"},
    {name: "react-reconciler", version: "0.33.0", licence: "MIT"},
    {name: "react-refresh", version: "0.14.2", licence: "MIT"},
    {name: "react-remove-scroll", version: "2.7.2", licence: "MIT", copyright: "Copyright (c) 2017 Anton Korzunov"},
    {name: "react-remove-scroll-bar", version: "2.3.8", licence: "MIT"},
    {name: "react-style-singleton", version: "2.2.3", licence: "MIT", copyright: "Copyright (c) 2017 Anton Korzunov"},
    {name: "redent", version: "3.0.0", licence: "MIT"},
    {name: "regenerate", version: "1.4.2", licence: "MIT"},
    {name: "regenerate-unicode-properties", version: "10.2.2", licence: "MIT"},
    {name: "regenerator-runtime", version: "0.13.11", licence: "MIT"},
    {name: "regexpu-core", version: "6.4.0", licence: "MIT"},
    {name: "regjsgen", version: "0.8.0", licence: "MIT", copyright: "Copyright 2014-2020 Benjamin Tan <https://ofcr.se/>"},
    {name: "regjsparser", version: "0.13.2", licence: "BSD-2-Clause"},
    {name: "require-directory", version: "2.1.1", licence: "MIT", copyright: "Copyright (c) 2011 Troy Goode <troygoode@gmail.com>"},
    {name: "resolve", version: "1.22.12", licence: "MIT", copyright: "Copyright (c) 2012 James Halliday"},
    {name: "resolve-cwd", version: "3.0.0", licence: "MIT"},
    {name: "resolve-from", version: "5.0.0", licence: "MIT"},
    {name: "resolve-workspace-root", version: "2.0.1", licence: "MIT"},
    {name: "resolve.exports", version: "2.0.3", licence: "MIT"},
    {name: "restore-cursor", version: "2.0.0", licence: "MIT"},
    {name: "safe-buffer", version: "5.2.1", licence: "MIT"},
    {name: "sandbox-cli-detector", version: "0.2.0", licence: "MIT", copyright: "Copyright (c) 2026 David Mokos"},
    {name: "sax", version: "1.6.1", licence: "BlueOak-1.0.0"},
    {name: "scheduler", version: "0.27.0", licence: "MIT"},
    {name: "semver", version: "6.3.1, 7.8.5", licence: "ISC"},
    {name: "send", version: "0.19.2", licence: "MIT", copyright: "Copyright (c) 2012 TJ Holowaychuk"},
    {name: "serialize-error", version: "2.1.0", licence: "MIT"},
    {name: "serve-static", version: "1.16.3", licence: "MIT", copyright: "Copyright (c) 2010 Sencha Inc."},
    {name: "server-only", version: "0.0.1", licence: "MIT"},
    {name: "set-function-length", version: "1.2.2", licence: "MIT"},
    {name: "setprototypeof", version: "1.2.0", licence: "ISC", copyright: "Copyright (c) 2015, Wes Todd"},
    {name: "sf-symbols-typescript", version: "2.2.0", licence: "MIT", copyright: "Copyright (c) 2023 Fernando Rojo"},
    {name: "shallowequal", version: "1.1.0", licence: "MIT", copyright: "Copyright (c) 2017 Alberto Leal <mailforalberto@gmail.com> (github.com/dashed)"},
    {name: "shebang-command", version: "2.0.0", licence: "MIT"},
    {name: "shebang-regex", version: "3.0.0", licence: "MIT"},
    {name: "shell-quote", version: "1.10.0", licence: "MIT", copyright: "Copyright (c) 2013 James Halliday (mail@substack.net)"},
    {name: "signal-exit", version: "3.0.7", licence: "ISC", copyright: "Copyright (c) 2015, Contributors"},
    {name: "simple-plist", version: "1.3.1", licence: "MIT", copyright: "Copyright (c) 2013 Joe Wollard"},
    {name: "simple-swizzle", version: "0.2.4", licence: "MIT", copyright: "Copyright (c) 2015 Josh Junon"},
    {name: "sisteransi", version: "1.0.5", licence: "MIT"},
    {name: "slash", version: "2.0.0, 3.0.0", licence: "MIT"},
    {name: "slugify", version: "1.6.9", licence: "MIT"},
    {name: "source-map", version: "0.5.7, 0.6.1", licence: "BSD-3-Clause", copyright: "Copyright (c) 2009-2011, Mozilla Foundation and contributors"},
    {name: "source-map-js", version: "1.2.1", licence: "BSD-3-Clause", copyright: "Copyright (c) 2009-2011, Mozilla Foundation and contributors"},
    {name: "source-map-support", version: "0.5.13, 0.5.21", licence: "MIT", copyright: "Copyright (c) 2014 Evan Wallace"},
    {name: "split-on-first", version: "1.1.0", licence: "MIT"},
    {name: "sprintf-js", version: "1.0.3", licence: "BSD-3-Clause", copyright: "Copyright (c) 2007-2014, Alexandru Marasteanu <hello [at) alexei (dot] ro>"},
    {name: "stack-utils", version: "2.0.6", licence: "MIT", copyright: "Copyright (c) 2016-2022 Isaac Z. Schlueter <i@izs.me>, James Talmage <james@talmage.io> (github.com/jamestalmage), and Contributors"},
    {name: "stackframe", version: "1.3.4", licence: "MIT", copyright: "Copyright (c) 2017 Eric Wendelin and other contributors"},
    {name: "stacktrace-parser", version: "0.1.11", licence: "MIT", copyright: "Copyright (c) 2014-2019 Georg Tavonius"},
    {name: "standard-navigation", version: "0.0.5", licence: "MIT"},
    {name: "statuses", version: "1.5.0, 2.0.2", licence: "MIT", copyright: "Copyright (c) 2014 Jonathan Ong <me@jongleberry.com>"},
    {name: "stream-buffers", version: "2.2.0", licence: "Unlicense"},
    {name: "strict-uri-encode", version: "2.0.0", licence: "MIT"},
    {name: "string-length", version: "4.0.2", licence: "MIT"},
    {name: "string-width", version: "4.2.3", licence: "MIT"},
    {name: "strip-ansi", version: "5.2.0, 6.0.1", licence: "MIT"},
    {name: "strip-bom", version: "4.0.0", licence: "MIT"},
    {name: "strip-final-newline", version: "2.0.0", licence: "MIT"},
    {name: "strip-indent", version: "3.0.0", licence: "MIT"},
    {name: "strip-json-comments", version: "3.1.1", licence: "MIT"},
    {name: "structured-headers", version: "0.4.1", licence: "MIT"},
    {name: "supports-color", version: "5.5.0, 7.2.0, 8.1.1", licence: "MIT"},
    {name: "supports-hyperlinks", version: "2.3.0", licence: "MIT"},
    {name: "supports-preserve-symlinks-flag", version: "1.0.0", licence: "MIT", copyright: "Copyright (c) 2022 Inspect JS"},
    {name: "tamagui", version: "2.7.7", licence: "MIT", copyright: "Copyright (c) 2020 Nate Wienert"},
    {name: "terminal-link", version: "2.1.1", licence: "MIT"},
    {name: "terser", version: "5.50.0", licence: "BSD-2-Clause", copyright: "Copyright 2012-2018 (c) Mihai Bazon <mihai.bazon@gmail.com>"},
    {name: "test-exclude", version: "6.0.0", licence: "ISC", copyright: "Copyright (c) 2016, Contributors"},
    {name: "test-renderer", version: "1.2.0", licence: "MIT"},
    {name: "throat", version: "5.0.0", licence: "MIT", copyright: "Copyright (c) 2013 Forbes Lindesay"},
    {name: "tinyglobby", version: "0.2.17", licence: "MIT", copyright: "Copyright (c) 2024 Madeline Gurriar\u00e1n"},
    {name: "tmp", version: "0.2.7", licence: "MIT", copyright: "Copyright (c) 2014 KARASZI Istv\u00e1n"},
    {name: "tmpl", version: "1.0.5", licence: "BSD-3-Clause"},
    {name: "to-regex-range", version: "5.0.1", licence: "MIT"},
    {name: "toidentifier", version: "1.0.1", licence: "MIT", copyright: "Copyright (c) 2016 Douglas Christopher Wilson <doug@somethingdoug.com>"},
    {name: "toqr", version: "0.1.1", licence: "MIT", copyright: "Copyright (c) 650 Industries, Inc. (aka Expo),"},
    {name: "tslib", version: "2.8.1", licence: "0BSD"},
    {name: "type-detect", version: "4.0.8", licence: "MIT", copyright: "Copyright (c) 2013 Jake Luer <jake@alogicalparadox.com> (http://alogicalparadox.com)"},
    {name: "type-fest", version: "0.21.3, 0.7.1", licence: "(MIT OR CC0-1.0)"},
    {name: "typescript", version: "6.0.3", licence: "Apache-2.0"},
    {name: "undici-types", version: "8.3.0", licence: "MIT"},
    {name: "unicode-canonical-property-names-ecmascript", version: "2.0.1", licence: "MIT"},
    {name: "unicode-match-property-ecmascript", version: "2.0.0", licence: "MIT"},
    {name: "unicode-match-property-value-ecmascript", version: "2.2.1", licence: "MIT"},
    {name: "unicode-property-aliases-ecmascript", version: "2.2.0", licence: "MIT"},
    {name: "universalify", version: "2.0.1", licence: "MIT", copyright: "Copyright (c) 2017, Ryan Zimmerman <opensrc@ryanzim.com>"},
    {name: "unpipe", version: "1.0.0", licence: "MIT", copyright: "Copyright (c) 2015 Douglas Christopher Wilson <doug@somethingdoug.com>"},
    {name: "update-browserslist-db", version: "1.3.1", licence: "MIT", copyright: "Copyright 2022 Andrey Sitnik <andrey@sitnik.es> and other contributors"},
    {name: "use-callback-ref", version: "1.3.3", licence: "MIT", copyright: "Copyright (c) 2017 Anton Korzunov"},
    {name: "use-latest-callback", version: "0.2.6", licence: "MIT", copyright: "Copyright (c) 2023 Satyajit Sahoo"},
    {name: "use-sidecar", version: "1.1.3", licence: "MIT", copyright: "Copyright (c) 2017 Anton Korzunov"},
    {name: "utils-merge", version: "1.0.1", licence: "MIT", copyright: "Copyright (c) 2013-2017 Jared Hanson"},
    {name: "uuid", version: "7.0.3", licence: "MIT", copyright: "Copyright (c) 2010-2016 Robert Kieffer and other contributors"},
    {name: "v8-to-istanbul", version: "9.3.0", licence: "ISC", copyright: "Copyright (c) 2017, Contributors"},
    {name: "validate-npm-package-name", version: "5.0.1", licence: "ISC", copyright: "Copyright (c) 2015, npm, Inc"},
    {name: "vary", version: "1.1.2", licence: "MIT", copyright: "Copyright (c) 2014-2017 Douglas Christopher Wilson"},
    {name: "vaul", version: "1.1.2", licence: "MIT", copyright: "Copyright (c) 2023 Emil Kowalski"},
    {name: "vlq", version: "1.0.1", licence: "MIT", copyright: "Copyright (c) 2017 [these people](https://github.com/Rich-Harris/vlq/graphs/contributors)"},
    {name: "walker", version: "1.0.8", licence: "Apache-2.0", copyright: "Copyright 2013 Naitik Shah"},
    {name: "warn-once", version: "0.1.1", licence: "MIT", copyright: "Copyright (c) 2022 Satyajit Sahoo"},
    {name: "wcwidth", version: "1.0.1", licence: "MIT", copyright: "Copyright (C) 2012 by Jun Woong."},
    {name: "whatwg-fetch", version: "3.6.20", licence: "MIT", copyright: "Copyright (c) 2014-2023 GitHub, Inc."},
    {name: "whatwg-url-minimum", version: "0.1.2", licence: "MIT", copyright: "Copyright (c) 650 Industries, Inc. (aka Expo),"},
    {name: "which", version: "2.0.2", licence: "ISC"},
    {name: "wrap-ansi", version: "7.0.0", licence: "MIT"},
    {name: "wrappy", version: "1.0.2", licence: "ISC"},
    {name: "write-file-atomic", version: "4.0.2", licence: "ISC", copyright: "Copyright (c) 2015, Rebecca Turner"},
    {name: "ws", version: "7.5.13, 8.21.3", licence: "MIT", copyright: "Copyright (c) 2011 Einar Otto Stangvik <einaros@gmail.com>"},
    {name: "xcode", version: "3.0.1", licence: "Apache-2.0"},
    {name: "xml2js", version: "0.6.0", licence: "MIT", copyright: "Copyright 2010, 2011, 2012, 2013. All rights reserved."},
    {name: "xmlbuilder", version: "11.0.1, 15.1.1", licence: "MIT", copyright: "Copyright (c) 2013 Ozgur Ozcitak"},
    {name: "y18n", version: "5.0.8", licence: "ISC", copyright: "Copyright (c) 2015, Contributors"},
    {name: "yallist", version: "3.1.1", licence: "ISC"},
    {name: "yaml", version: "2.9.0", licence: "ISC"},
    {name: "yargs", version: "17.7.3", licence: "MIT", copyright: "Copyright 2010 James Halliday (mail@substack.net); Modified work Copyright 2014 Contributors (ben@npmjs.com)"},
    {name: "yargs-parser", version: "21.1.1", licence: "ISC", copyright: "Copyright (c) 2016, Contributors"},
    {name: "yocto-queue", version: "0.1.0", licence: "MIT"},
    {name: "zod", version: "3.25.76", licence: "MIT", copyright: "Copyright (c) 2025 Colin McDonnell"},
];
