const {withDangerousMod} = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const ANCHOR = 'prepare_react_native_project!';
const DIRECTIVE = 'inhibit_all_warnings!';

/**
 * A clean build emits ~600 warnings on the simulator (more for device, which
 * builds additional architectures), and every single one comes from a
 * dependency - expo-sqlite, react-native-svg and expo-dev-launcher account for
 * most of them. None come from this project's own code, so they are pure noise
 * that hides anything we might actually introduce.
 *
 * CocoaPods can silence them wholesale, but the Podfile is generated by
 * prebuild (CNG), so the directive has to be injected here rather than
 * committed.
 */
module.exports = function withInhibitPodWarnings(config) {
    return withDangerousMod(config, [
        'ios',
        async (cfg) => {
            const podfile = path.join(cfg.modRequest.platformProjectRoot, 'Podfile');
            const contents = fs.readFileSync(podfile, 'utf8');

            if (contents.includes(DIRECTIVE)) {
                return cfg;
            }
            if (!contents.includes(ANCHOR)) {
                throw new Error(
                    `[withInhibitPodWarnings] Could not find "${ANCHOR}" in the Podfile. ` +
                    `The Expo Podfile template changed; update this plugin.`
                );
            }

            fs.writeFileSync(
                podfile,
                contents.replace(ANCHOR, `${DIRECTIVE}\n\n${ANCHOR}`)
            );
            return cfg;
        }
    ]);
};
